import NumStability.Algorithms.NormEstimation.PNorm.Convergence.BoydConcrete
import NumStability.Algorithms.NormEstimation.PNorm.Convergence.BoydInterface
import NumStability.Algorithms.NormEstimation.PNorm.Convergence.ConvergenceStatements
import NumStability.Algorithms.NormEstimation.PNorm.Duality.BoydInterface
import NumStability.Algorithms.NormEstimation.PNorm.Duality.BoydUniqueness
import NumStability.Algorithms.NormEstimation.PNorm.Duality.ConvergenceStatements
import NumStability.Algorithms.NormEstimation.PNorm.Duality.PNormGeneral
import NumStability.Algorithms.NormEstimation.PNorm.Duality.PNormPowerMethod
import NumStability.Algorithms.NormEstimation.PNorm.Endpoints.ConvergenceStatements
import NumStability.Algorithms.NormEstimation.PNorm.Endpoints.PNormRectangular
import NumStability.Algorithms.NormEstimation.PNorm.PowerMethod.BoydConcrete
import NumStability.Algorithms.NormEstimation.PNorm.PowerMethod.BoydInterface
import NumStability.Algorithms.NormEstimation.PNorm.PowerMethod.PNormGeneral
import NumStability.Algorithms.NormEstimation.PNorm.PowerMethod.PNormPowerMethod
import NumStability.Algorithms.NormEstimation.PNorm.Rectangular.BoydInterface
import NumStability.Algorithms.NormEstimation.PNorm.Rectangular.PNormGeneral
import NumStability.Algorithms.NormEstimation.PNorm.Rectangular.PNormRectangular
import NumStability.Algorithms.NormEstimation.PNorm.Rectangular.RectangularTermination

/-!
# p-norm power method

Reusable p-norm construction, duality,
convergence and endpoint material.
-/

#check @NumStability.Ch15.HasDirectionalGradientAt
#check @NumStability.Ch15.IsRealLpNormer
#check @NumStability.Ch15.IsSubgradient
#check @NumStability.Ch15.PNormPair
#check @NumStability.Ch15.PNormPair.A
#check @NumStability.Ch15.PNormPair.casesOn
#check @NumStability.Ch15.PNormPair.ctorIdx
#check @NumStability.Ch15.PNormPair.dp
#check @NumStability.Ch15.PNormPair.dp_attains
#check @NumStability.Ch15.PNormPair.dp_isSubgradient
#check @NumStability.Ch15.PNormPair.dp_qunit
#check @NumStability.Ch15.PNormPair.dq
#check @NumStability.Ch15.PNormPair.dq_attains
#check @NumStability.Ch15.PNormPair.dq_punit
#check @NumStability.Ch15.PNormPair.gammaSeq
#check @NumStability.Ch15.PNormPair.holder
#check @NumStability.Ch15.PNormPair.mk
#check @NumStability.Ch15.PNormPair.mk.inj
#check @NumStability.Ch15.PNormPair.mk.injEq
#check @NumStability.Ch15.PNormPair.mk.noConfusion
#check @NumStability.Ch15.PNormPair.mk.sizeOf_spec
#check @NumStability.Ch15.PNormPair.noConfusion
#check @NumStability.Ch15.PNormPair.noConfusionType
#check @NumStability.Ch15.PNormPair.opP
#check @NumStability.Ch15.PNormPair.op_bound
#check @NumStability.Ch15.PNormPair.pN
#check @NumStability.Ch15.PNormPair.pN_nonneg
#check @NumStability.Ch15.PNormPair.qN
#check @NumStability.Ch15.PNormPair.rec
#check @NumStability.Ch15.PNormPair.recOn
#check @NumStability.Ch15.PNormPair.xnext
#check @NumStability.Ch15.PNormPair.xseq
#check @NumStability.Ch15.PNormPair.xseq_has_convergent_subsequence
#check @NumStability.Ch15.PNormPair.xseq_limit_is_fixed_of_continuousAt
#check @NumStability.Ch15.PNormPair.xseq_punit
#check @NumStability.Ch15.PNormPair.yof
#check @NumStability.Ch15.PNormPair.yof_sub
#check @NumStability.Ch15.PNormPair.z_dot
#check @NumStability.Ch15.PNormPair.zof
#check @NumStability.Ch15.SmoothPNormPair
#check @NumStability.Ch15.SmoothPNormPair.P
#check @NumStability.Ch15.SmoothPNormPair.casesOn
#check @NumStability.Ch15.SmoothPNormPair.composite_hasDirectionalGradientAt
#check @NumStability.Ch15.SmoothPNormPair.conjugate
#check @NumStability.Ch15.SmoothPNormPair.ctorIdx
#check @NumStability.Ch15.SmoothPNormPair.dp_qnorm_one
#check @NumStability.Ch15.SmoothPNormPair.general
#check @NumStability.Ch15.SmoothPNormPair.mk
#check @NumStability.Ch15.SmoothPNormPair.mk.inj
#check @NumStability.Ch15.SmoothPNormPair.mk.injEq
#check @NumStability.Ch15.SmoothPNormPair.mk.noConfusion
#check @NumStability.Ch15.SmoothPNormPair.mk.sizeOf_spec
#check @NumStability.Ch15.SmoothPNormPair.noConfusion
#check @NumStability.Ch15.SmoothPNormPair.noConfusionType
#check @NumStability.Ch15.SmoothPNormPair.one_lt_p
#check @NumStability.Ch15.SmoothPNormPair.one_lt_q
#check @NumStability.Ch15.SmoothPNormPair.p
#check @NumStability.Ch15.SmoothPNormPair.pN_gradient
#check @NumStability.Ch15.SmoothPNormPair.pN_pos
#check @NumStability.Ch15.SmoothPNormPair.pN_zero
#check @NumStability.Ch15.SmoothPNormPair.q
#check @NumStability.Ch15.SmoothPNormPair.rec
#check @NumStability.Ch15.SmoothPNormPair.recOn
#check @NumStability.Ch15.SmoothPNormPair.two
#check @NumStability.Ch15.abs_dot_normalize2_smul
#check @NumStability.Ch15.continuousAt_realLpDual
#check @NumStability.Ch15.continuousAt_realLpDualUnit
#check @NumStability.Ch15.continuousAt_realLpGradient
#check @NumStability.Ch15.continuous_realLpGradient_coordFactor
#check @NumStability.Ch15.continuous_realLpPowerSum
#check @NumStability.Ch15.continuous_realLpSignedPower
#check @NumStability.Ch15.continuous_realVecLpNorm
#check @NumStability.Ch15.e0Vec
#check @NumStability.Ch15.exists_nonincreasing_step_of_fin_labels
#check @NumStability.Ch15.exists_realLpNormer
#check @NumStability.Ch15.gammaSeq_one_succ_eq_column
#check @NumStability.Ch15.holder_inf
#check @NumStability.Ch15.holder_two
#check @NumStability.Ch15.infRowValue
#check @NumStability.Ch15.normalize2
#check @NumStability.Ch15.normalize2_attains
#check @NumStability.Ch15.normalize2_eq_self_of_unit
#check @NumStability.Ch15.normalize2_unit
#check @NumStability.Ch15.oneColumnValue
#check @NumStability.Ch15.opBound_two
#check @NumStability.Ch15.opNorm2_rankOne_eq
#check @NumStability.Ch15.pNormPair_general
#check @NumStability.Ch15.pNormPair_inf
#check @NumStability.Ch15.pNormPair_two
#check @NumStability.Ch15.qNorm_zof_inf_eq_row
#check @NumStability.Ch15.realLpDual
#check @NumStability.Ch15.realLpDualUnit
#check @NumStability.Ch15.realLpDualUnit_attains
#check @NumStability.Ch15.realLpDualUnit_norm_eq_one
#check @NumStability.Ch15.realLpDualUnit_pos_of_pos
#check @NumStability.Ch15.realLpDual_eq_realLpGradient
#check @NumStability.Ch15.realLpDual_isSubgradient
#check @NumStability.Ch15.realLpDual_nonneg_of_nonneg
#check @NumStability.Ch15.realLpDual_norm_eq_one
#check @NumStability.Ch15.realLpDual_pos_of_pos
#check @NumStability.Ch15.realLpDual_spec
#check @NumStability.Ch15.realLpGradient_coord_eq_rpow_sub_one_of_pos_unit
#check @NumStability.Ch15.realLpGradient_coord_eq_signedPower
#check @NumStability.Ch15.realLpGradient_nonneg_of_nonneg_coord
#check @NumStability.Ch15.realLpGradient_pos_of_pos_coord
#check @NumStability.Ch15.realLpNormalizedStart
#check @NumStability.Ch15.realLpNormalizedStart_norm_eq_one
#check @NumStability.Ch15.realLpNormalizedStart_pos
#check @NumStability.Ch15.realLpNormer_eq_dual
#check @NumStability.Ch15.realLpPowerSum_eq_one_of_unit
#check @NumStability.Ch15.realLpSignedPower
#check @NumStability.Ch15.realMatrixLpNorm
#check @NumStability.Ch15.realRectLpComposite_hasDirectionalGradientAt
#check @NumStability.Ch15.realRectLpComposite_isSubgradient
#check @NumStability.Ch15.realRectMatVec
#check @NumStability.Ch15.realRectMatVec_add_smul
#check @NumStability.Ch15.realRectTransposeVec
#check @NumStability.Ch15.realRectTranspose_pairing
#check @NumStability.Ch15.realVecLpNorm
#check @NumStability.Ch15.realVecLpNorm_basisVec
#check @NumStability.Ch15.realVecLpNorm_eq_sum_rpow
#check @NumStability.Ch15.realVecLpNorm_holder
#check @NumStability.Ch15.realVecLpNorm_pos
#check @NumStability.Ch15.realVecLpNorm_smul_real
#check @NumStability.Ch15.realVecLpNorm_zero
#check @NumStability.Ch15.rectPNormPair_xseq_eq_iterate
#check @NumStability.Ch15.rectPNormPair_xseq_shift_add
#check @NumStability.Ch15.rect_gammaSeq_bddAbove
#check @NumStability.Ch15.rpow_div_rpow_cancel
#check @NumStability.Ch15.rpow_one_sub_mul_rpow_sub_one
#check @NumStability.Ch15.rpow_sub_two_mul_self_eq_rpow_sub_one
#check @NumStability.Ch15.rpow_sub_two_mul_self_eq_rpow_sub_one_of_nonneg
#check @NumStability.Ch15.sign_infNorm_eq_one
#check @NumStability.Ch15.tendsto_iterate_of_compact_strictLyapunov_unique_fixed
#check @NumStability.Ch15.tendsto_rectPNormPair_xseq_of_tail
#check @NumStability.Ch15.unique_subgradient_of_directional_gradient
#check @NumStability.Ch15.vecNorm2_e0
#check @NumStability.Ch15.vecNorm2_hasDirectionalGradientAt
#check @NumStability.Ch15.vecNorm2_pos_of_ne
#check @NumStability.RectPNormPair
#check @NumStability.RectPNormPair.A
#check @NumStability.RectPNormPair.State
#check @NumStability.RectPNormPair.State.casesOn
#check @NumStability.RectPNormPair.State.ctorIdx
#check @NumStability.RectPNormPair.State.mk
#check @NumStability.RectPNormPair.State.mk.inj
#check @NumStability.RectPNormPair.State.mk.injEq
#check @NumStability.RectPNormPair.State.mk.noConfusion
#check @NumStability.RectPNormPair.State.mk.sizeOf_spec
#check @NumStability.RectPNormPair.State.noConfusion
#check @NumStability.RectPNormPair.State.noConfusionType
#check @NumStability.RectPNormPair.State.rec
#check @NumStability.RectPNormPair.State.recOn
#check @NumStability.RectPNormPair.State.x
#check @NumStability.RectPNormPair.State.γ
#check @NumStability.RectPNormPair.StopsAt
#check @NumStability.RectPNormPair.casesOn
#check @NumStability.RectPNormPair.ctorIdx
#check @NumStability.RectPNormPair.dpOut
#check @NumStability.RectPNormPair.dpOut_attains
#check @NumStability.RectPNormPair.dpOut_qunit
#check @NumStability.RectPNormPair.dqIn
#check @NumStability.RectPNormPair.dqIn_attains
#check @NumStability.RectPNormPair.dqIn_punit
#check @NumStability.RectPNormPair.gammaSeq
#check @NumStability.RectPNormPair.gammaSeq_le_opP
#check @NumStability.RectPNormPair.gammaSeq_one_succ_eq_column_rect
#check @NumStability.RectPNormPair.general
#check @NumStability.RectPNormPair.holderIn
#check @NumStability.RectPNormPair.holderOut
#check @NumStability.RectPNormPair.holder_inf
#check @NumStability.RectPNormPair.infNormVec_rectMatVec_le
#check @NumStability.RectPNormPair.infRowValueRect
#check @NumStability.RectPNormPair.infinity
#check @NumStability.RectPNormPair.mk
#check @NumStability.RectPNormPair.mk.inj
#check @NumStability.RectPNormPair.mk.injEq
#check @NumStability.RectPNormPair.mk.noConfusion
#check @NumStability.RectPNormPair.mk.sizeOf_spec
#check @NumStability.RectPNormPair.noConfusion
#check @NumStability.RectPNormPair.noConfusionType
#check @NumStability.RectPNormPair.one
#check @NumStability.RectPNormPair.oneColumnValueRect
#check @NumStability.RectPNormPair.oneNormVec_rectMatVec_le
#check @NumStability.RectPNormPair.opP
#check @NumStability.RectPNormPair.op_bound
#check @NumStability.RectPNormPair.pIn
#check @NumStability.RectPNormPair.pIn_nonneg
#check @NumStability.RectPNormPair.pOut
#check @NumStability.RectPNormPair.pOut_nonneg
#check @NumStability.RectPNormPair.powerStep
#check @NumStability.RectPNormPair.powerStep_gamma_eq
#check @NumStability.RectPNormPair.qIn
#check @NumStability.RectPNormPair.qIn_zof_infinity_eq_row_rect
#check @NumStability.RectPNormPair.qOut
#check @NumStability.RectPNormPair.realRectMatrixLpNorm
#check @NumStability.RectPNormPair.rec
#check @NumStability.RectPNormPair.recOn
#check @NumStability.RectPNormPair.signVec_infNorm_eq_one
#check @NumStability.RectPNormPair.xnext
#check @NumStability.RectPNormPair.xseq
#check @NumStability.RectPNormPair.xseq_punit
#check @NumStability.RectPNormPair.yof
#check @NumStability.RectPNormPair.z_dot
#check @NumStability.RectPNormPair.zof
#check @NumStability.RectPNormPair.zof_infinity_eq_signed_selected_row_rect
