import NumStability.Analysis.MatrixEquations.SylvesterExistence
import NumStability.Source.Higham.Chapter09.Problems
import NumStability.Source.Higham.Chapter09.Theorem14.Actual
import NumStability.Source.Higham.Chapter09.Theorem14.Primitive
import NumStability.Source.Higham.Chapter11.Bunch.ExactTrace
import NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge
import NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard
import NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth
import NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Trace
import NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve
import NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.TerminalClosedForm
import NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth
import NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.TerminalClosedForm
import NumStability.Source.Higham.Chapter11.BunchKaufman.SourceCorrection
import NumStability.Source.Higham.Chapter11.Skew.SourceCorrection
import NumStability.Source.Higham.Chapter16.Foundations.Core
import NumStability.Source.Higham.Chapter16.Minimizers.Results
import NumStability.Source.Higham.Chapter16.Problem02.Results.Core
import NumStability.Source.Higham.Chapter16.QuasiRounded.Solve
import NumStability.Source.Higham.Chapter16.Spectrum.Results
import NumStability.Source.Higham.Chapter16.VecPermutation.Notes

/-!
# R06 approved private normalization (exhaustive)

Constructs all 200 approved post-delivery private names and requires each to
be present in the environment. It separately requires only the 195 genuine
rename pre-images to be absent; the five amended identity rows remain present.
-/

private def appendNameParts (baseName : Lean.Name) (parts : List String) : Lean.Name :=
  parts.foldl (fun name part => .str name part) baseName

private def mangledPrivateName (moduleName declarationName : String)
    (ordinal : Nat) : Lean.Name :=
  let modulePrefix := appendNameParts .anonymous ("_private" :: moduleName.splitOn ".")
  appendNameParts (.num modulePrefix ordinal) (declarationName.splitOn ".")

private def approvedPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Foundations.Core" "NumStability.rectMatMul_left_right_sub" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Foundations.Core" "NumStability.sylvesterVecCoeff_det_ne_zero_of_pos_le_sylvesterSepInf" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Foundations.Core" "NumStability.sylvesterVecCoeff_det_ne_zero_of_sepLowerBound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.abs_sub_add_add_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_pairFst" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_pairFst_entry" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_pairSnd" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_pairSnd_entry" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleFst" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleFst_entry" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleSndFst" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleSndFst_entry" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleSndSnd" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.continuous_tripleSndSnd_entry" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.isBackwardError_sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.isClosed_lyapunovBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.isClosed_sylvesterBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.isLyapunovBackwardError_lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.lyapunovBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.lyapunovBackwardObjective_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.lyapunovBackwardObjective_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.sq_le_sq_of_nonneg_of_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.sylvesterBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.sylvesterBackwardObjective_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Minimizers.Results" "NumStability.sylvesterBackwardObjective_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16Problem16_2QuadraticCLM" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16Problem16_2QuadraticComplexLinear" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_eventually_norm_pow_le_of_spectralRadius_lt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_exists_uniform_geometric_power_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_kernel_integrable_of_exp_decay" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_neg_one_hurwitz" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_normSq_add_real" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_norm_exp_smul_le_of_uniform_power_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_problem16_2_integral_posDef_of_pointwise" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_problem16_2_kernel_deriv_integrableOn" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_problem16_2_quadraticCLM_apply" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_problem16_2_quadraticComplexLinear_apply" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Problem02.Results.Core" "NumStability.higham16_zero_posSemidef_not_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.QuasiRounded.Solve" "NumStability.Wave15.solve2x2_core" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.column_sum_split_of_zero_below" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.mulVec_injective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.mulVec_surjective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.rectMatMul_schur_coords_expand_for_triangular" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.triangular_column_sum_split" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.Spectrum.Results" "NumStability.two_column_block_sum_split" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter16.VecPermutation.Notes" "NumStability.higham16_sum_swap_indicator" 0,
  mangledPrivateName "NumStability.Analysis.MatrixEquations.SylvesterExistence" "NumStability.complexSylvesterVecCoeffDualIndexEquiv" 0,
  mangledPrivateName "NumStability.Analysis.MatrixEquations.SylvesterExistence" "NumStability.complex_mulVec_injective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Analysis.MatrixEquations.SylvesterExistence" "NumStability.complex_mulVec_surjective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_abs_add_eq_add_abs_of_mul_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_actualFactor_abs_diag_le_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_actualFactor_abs_sub_le_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_exact_LU_diag_rel" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_exact_LU_sub_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_14_exact_LU_super_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_21_lower_row_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_21_lower_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_21_upper_last_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_21_upper_row_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Actual" "NumStability.higham9_21_upper_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Primitive" "NumStability.higham9_14_div_input_stability" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Primitive" "NumStability.higham9_14_exists_finite_source_bounds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Primitive" "NumStability.higham9_14_pivotErrorBudget_le_final" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Primitive" "NumStability.higham9_14_pivotErrorBudget_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem14.Primitive" "NumStability.higham9_14_roundedPivot_step_error" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.ExactTrace" "NumStability.Higham11ExactBunchTrace.bunchAlpha_sq_le_one_sub_sq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.Higham11RoundedBunchKaufmanExecution.flatAbsProduct_le_thirtySix_dimension_stageMax" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockOne_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockOne_absProduct_0s" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockOne_absProduct_s0" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockOne_global_budget_thirtySix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_01" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_11" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_pp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_pt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_absProduct_tp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Growth" "NumStability.blockTwo_global_budget_thirtySix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Exact.Trace" "NumStability.higham11_2_bunchKaufmanOmegaOne_pos_of_branch" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve" "NumStability.abs_one_add_le_one_add" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve" "NumStability.explicitInverse_diagonal_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve" "NumStability.explicitInverse_mu_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve" "NumStability.explicitInverse_scaled_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.Solve" "NumStability.one_sub_le_one_add" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.ExplicitInverse.TerminalClosedForm" "NumStability.Higham11RoundedBunchKaufmanExecution.explicitInverse_terminal_input_envelope_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.Higham11RoundedBunchKaufmanExecution.flatAbsProduct_le_forty_mul_dimension_mul_roundedStageMax_aux" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockOne_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockOne_absProduct_0s" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockOne_absProduct_global_budget" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockOne_absProduct_s0" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockTwo_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockTwo_absProduct_01" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockTwo_absProduct_10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockTwo_absProduct_11" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_blockTwo_absProduct_global_budget" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_bunchAlpha_le_two_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_case4_four_term_path_le_thirtyThree" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_perturbed_case4_solve_component_bounds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_relative_product_perturbation" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.Growth" "NumStability.higham11_4_two_mul_currentMax_of_omega_div_alpha" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.TerminalClosedForm" "NumStability.Higham11RoundedBunchKaufmanExecution.terminal_input_envelope_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.SourceCorrection" "NumStability.higham11_4_sourceCorrectionOneMatrix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.BunchKaufman.SourceCorrection" "NumStability.higham11_4_sourceCorrectionTwoMatrix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedLogSum_le_log_detProduct" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedMean_cons_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedMean_sub_log_first_le_half_log" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjusted_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.block_adjusted_log_le_log_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.block_penalty_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.boundaryMoment_core_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.boundaryMoment_total_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.certificate_hadamard" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.detProduct_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.eliminatedWidth_lt_totalWidth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.last_log_sub_first_log_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.local_adjusted_gap_scaled" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.local_log_growth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_d_add_two_div_d_add_one_le_five_twelfths" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_d_add_two_ratio_le_one_fourth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_five_le_five_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_four_ge_four_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_symmetric_ratio_lower" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_wilkinson_bound_eq_steps" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.one_div_le_log_self_div_pred" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.one_sub_alpha_sq_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.sharp_potential_add_half_log_eq_log_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.small_adjusted_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.small_numeric_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_one_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_two_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_two_raw_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.wilkinsonLogSteps_succ" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_ge_16_div_25" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_ge_6403_div_10000" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_inv_sq_le_307_div_100" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchLocalGrowthFactor_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchLocalGrowthFactor_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyOne_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyTwo_le_27_div_100" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyTwo_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_bunch_harmonic_penalty_le_sharp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_log_307_div_100_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_log_bunchLocalGrowthFactor_le_19_div_20" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_log_three_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_log_two_ge_two_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_neg_log_bunchAlpha_le_223_div_500" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.SharpGrowthBridge" "NumStability.higham11_1_one_sub_bunchAlpha_sq_ge_589_div_1000" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.det_submatrix_self_of_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.emptyPrefixPrincipalMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.exists_diagonal_max" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneBottomLeft" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneLiftSum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneLiftSum_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.onePivotBlock" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.onePivotBlock_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.onePivotInv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneSourceLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneSourceLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneTailMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.oneTopRight" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.one_schur_selected_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.one_selected_block_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.one_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.one_source_full_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.one_source_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoBottomLeft" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoHead" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoHead_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoHead_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoLiftSum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoLiftSum_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoPivotBlock" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoPivotBlock_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoPivotBlock_mul_inv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoPivotInv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoSourceLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoSourceLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoTailMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.twoTopRight" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.two_schur_selected_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.two_selected_block_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.two_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.two_source_full_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Bunch.TraceHadamard" "NumStability.two_source_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Skew.SourceCorrection" "NumStability.higham11_9_twoColumnCounterexample_score_eq_two" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Skew.SourceCorrection" "NumStability.higham11_9_twoColumnCounterexample_score_le_two" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Problems" "NumStability.higham9_6_adjacent_chain_shift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Problems" "NumStability.higham9_8_strictMono_fin_self_eq_id" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Problems" "NumStability.higham9_8_succAbove_checkerboard_sign_products" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Problems" "NumStability.higham9_finMaskedPrefixSum_eq_finSum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Problems" "NumStability.higham_problem9_3_quadraticForm_embedded_leading_kernel_eq_zero" 0
]

private def retiredPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16" "NumStability.rectMatMul_left_right_sub" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16" "NumStability.sylvesterVecCoeff_det_ne_zero_of_pos_le_sylvesterSepInf" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16" "NumStability.sylvesterVecCoeff_det_ne_zero_of_sepLowerBound" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.abs_sub_add_add_le" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_pairFst" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_pairFst_entry" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_pairSnd" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_pairSnd_entry" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleFst" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleFst_entry" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleSndFst" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleSndFst_entry" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleSndSnd" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.continuous_tripleSndSnd_entry" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.isBackwardError_sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.isClosed_lyapunovBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.isClosed_sylvesterBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.isLyapunovBackwardError_lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.lyapunovBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.lyapunovBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.lyapunovBackwardObjective_le" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.lyapunovBackwardObjective_nonneg" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.sq_le_sq_of_nonneg_of_le" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.sylvesterBackwardFeasibleSet" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.sylvesterBackwardObjective" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.sylvesterBackwardObjective_le" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Minimizers" "NumStability.sylvesterBackwardObjective_nonneg" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16Problem16_2QuadraticCLM" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16Problem16_2QuadraticComplexLinear" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_eventually_norm_pow_le_of_spectralRadius_lt" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_exists_uniform_geometric_power_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_kernel_integrable_of_exp_decay" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_neg_one_hurwitz" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_normSq_add_real" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_norm_exp_smul_le_of_uniform_power_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_problem16_2_integral_posDef_of_pointwise" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_problem16_2_kernel_deriv_integrableOn" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_problem16_2_quadraticCLM_apply" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_problem16_2_quadraticComplexLinear_apply" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Problem16_2" "NumStability.higham16_zero_posSemidef_not_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16QuasiRoundedSolve" "NumStability.Wave15.solve2x2_core" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.column_sum_split_of_zero_below" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.mulVec_injective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.mulVec_surjective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.rectMatMul_schur_coords_expand_for_triangular" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.triangular_column_sum_split" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16Spectrum" "NumStability.two_column_block_sum_split" 0,
  mangledPrivateName "NumStability.Algorithms.Sylvester.Higham16VecPermutationNotes" "NumStability.higham16_sum_swap_indicator" 0,
  mangledPrivateName "NumStability.Analysis.SylvesterSchurExistence" "NumStability.complexSylvesterVecCoeffDualIndexEquiv" 0,
  mangledPrivateName "NumStability.Analysis.SylvesterSchurExistence" "NumStability.complex_mulVec_injective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Analysis.SylvesterSchurExistence" "NumStability.complex_mulVec_surjective_of_det_ne_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_abs_add_eq_add_abs_of_mul_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_actualFactor_abs_diag_le_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_actualFactor_abs_sub_le_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_exact_LU_diag_rel" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_exact_LU_sub_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_14_exact_LU_super_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_21_lower_row_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_21_lower_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_21_upper_last_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_21_upper_row_sum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Actual" "NumStability.higham9_21_upper_step_corrected" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Primitive" "NumStability.higham9_14_div_input_stability" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Primitive" "NumStability.higham9_14_exists_finite_source_bounds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Primitive" "NumStability.higham9_14_pivotErrorBudget_le_final" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Primitive" "NumStability.higham9_14_pivotErrorBudget_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter09.Theorem914Primitive" "NumStability.higham9_14_roundedPivot_step_error" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchExactTrace" "NumStability.Higham11ExactBunchTrace.bunchAlpha_sq_le_one_sub_sq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.Higham11RoundedBunchKaufmanExecution.flatAbsProduct_le_thirtySix_dimension_stageMax" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockOne_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockOne_absProduct_0s" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockOne_absProduct_s0" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockOne_global_budget_thirtySix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_01" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_11" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_pp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_pt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_absProduct_tp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactGrowth" "NumStability.blockTwo_global_budget_thirtySix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExactTrace" "NumStability.higham11_2_bunchKaufmanOmegaOne_pos_of_branch" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseSolve" "NumStability.abs_one_add_le_one_add" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseSolve" "NumStability.explicitInverse_diagonal_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseSolve" "NumStability.explicitInverse_mu_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseSolve" "NumStability.explicitInverse_scaled_ratio_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseSolve" "NumStability.one_sub_le_one_add" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseTerminalClosedForm" "NumStability.Higham11RoundedBunchKaufmanExecution.explicitInverse_terminal_input_envelope_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.Higham11RoundedBunchKaufmanExecution.flatAbsProduct_le_forty_mul_dimension_mul_roundedStageMax_aux" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockOne_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockOne_absProduct_0s" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockOne_absProduct_global_budget" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockOne_absProduct_s0" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockTwo_absProduct_00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockTwo_absProduct_01" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockTwo_absProduct_10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockTwo_absProduct_11" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_blockTwo_absProduct_global_budget" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_bunchAlpha_le_two_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_case4_four_term_path_le_thirtyThree" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_perturbed_case4_solve_component_bounds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_relative_product_perturbation" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedGrowth" "NumStability.higham11_4_two_mul_currentMax_of_omega_div_alpha" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanRoundedTerminalClosedForm" "NumStability.Higham11RoundedBunchKaufmanExecution.terminal_input_envelope_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanSourceCorrection" "NumStability.higham11_4_sourceCorrectionOneMatrix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanSourceCorrection" "NumStability.higham11_4_sourceCorrectionTwoMatrix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedLogSum_le_log_detProduct" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedMean_cons_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjustedMean_sub_log_first_le_half_log" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.adjusted_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.block_adjusted_log_le_log_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.block_penalty_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.boundaryMoment_core_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.boundaryMoment_total_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.certificate_hadamard" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.detProduct_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.eliminatedWidth_lt_totalWidth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.last_log_sub_first_log_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.local_adjusted_gap_scaled" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.local_log_growth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_d_add_two_div_d_add_one_le_five_twelfths" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_d_add_two_ratio_le_one_fourth" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_five_le_five_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_four_ge_four_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_symmetric_ratio_lower" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.log_wilkinson_bound_eq_steps" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.one_div_le_log_self_div_pred" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.one_sub_alpha_sq_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.sharp_potential_add_half_log_eq_log_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.small_adjusted_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.small_numeric_gap_le_potential" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_one_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_two_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.width_two_raw_potential_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.Higham11BunchSharpBlockCertificate.wilkinsonLogSteps_succ" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_ge_16_div_25" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_ge_6403_div_10000" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchAlpha_inv_sq_le_307_div_100" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchLocalGrowthFactor_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchLocalGrowthFactor_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyOne_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyTwo_le_27_div_100" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunchPenaltyTwo_le_exponent" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_bunch_harmonic_penalty_le_sharp" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_log_307_div_100_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_log_bunchLocalGrowthFactor_le_19_div_20" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_log_three_ge_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_log_two_ge_two_thirds" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_neg_log_bunchAlpha_le_223_div_500" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchSharpGrowthBridge" "NumStability.higham11_1_one_sub_bunchAlpha_sq_ge_589_div_1000" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.det_submatrix_self_of_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.emptyPrefixPrincipalMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.exists_diagonal_max" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneBottomLeft" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneLiftSum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneLiftSum_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.onePivotBlock" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.onePivotBlock_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.onePivotInv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneSourceLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneSourceLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneTailMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.oneTopRight" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.one_schur_selected_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.one_selected_block_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.one_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.one_source_full_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.one_source_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoBottomLeft" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoHead" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoHead_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoHead_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoLiftSum" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoLiftSum_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoPivotBlock" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoPivotBlock_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoPivotBlock_mul_inv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoPivotInv" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoSourceLift" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoSourceLift_injective" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoTailMinor" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.twoTopRight" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.two_schur_selected_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.two_selected_block_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.two_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.two_source_full_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11BunchTraceHadamard" "NumStability.two_source_selected_det_step" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11SkewSourceCorrection" "NumStability.higham11_9_twoColumnCounterexample_score_eq_two" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter11.Higham11SkewSourceCorrection" "NumStability.higham11_9_twoColumnCounterexample_score_le_two" 0
]

run_cmd do
  let environment ← Lean.getEnv
  for name in approvedPrivateNames do
    unless Lean.Environment.contains environment name do
      throwError "R06 private normalization: missing approved name {name}"
  for name in retiredPrivateNames do
    if Lean.Environment.contains environment name then
      throwError "R06 private normalization: retired name {name} still present"
