import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.SpectralTransfer.Elementwise

/-!
# W11 NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.SpectralTransfer.Elementwise test
-/

#check @NumStability.FiniteProbability.expectationReal_vecNorm2_le_prod_expectationReal_vecNorm2_sub_of_expectation_eq_zero
