import NumStability.Algorithms.HighamChapter8

/-!
# R03 historical-only test — `HighamChapter8`

Imports exactly the historical path; checks its preserved public
surface (55 declarations).
-/

#check @NumStability.higham8_12_WInv_le_ZInvFormula
#check @NumStability.higham8_12_absolute_norm_vector_chain
#check @NumStability.higham8_12_comparisonInv_le_WInv
#check @NumStability.higham8_12_infNorm_chain
#check @NumStability.higham8_12_oneNorm_chain
#check @NumStability.higham8_12_opNorm2_chain
#check @NumStability.higham8_14_full_norm_chain
#check @NumStability.higham8_14_local_envelope_not_relative_after_cancellation
#check @NumStability.higham8_14_oneNorm_upperBound
#check @NumStability.higham8_14_opNorm2_upperBound
#check @NumStability.higham8_2_backSub_anyOrder_relative_infNorm_bound
#check @NumStability.higham8_2_backSub_relative_infNorm_bound
#check @NumStability.higham8_2_comparisonInverseInfNormRatio_ge_lambda
#check @NumStability.higham8_2_comparisonInverseOneNormRatio_ge_lambda
#check @NumStability.higham8_2_comparisonInverseRatios_arbitrarily_large
#check @NumStability.higham8_2_forwardSub_anyOrder_relative_infNorm_bound
#check @NumStability.higham8_2_forwardSub_relative_infNorm_bound
#check @NumStability.higham8_4_upperTriangularMMatrix_condAtSolution_le
#check @NumStability.higham8_6_comparisonInverseAbsVecInfNorm_le_WInverseAbsVecInfNorm
#check @NumStability.higham8_6_comparisonInverseAbsVec_le_WInverseAbsVec
#check @NumStability.higham8_7_comparisonInverseOnes_infNorm_ge_inverseInfNorm
#check @NumStability.higham8_7_scaledStrictRowDiagDominant_invInfNorm_le
#check @NumStability.higham8_7_strictRowDiagDominant_invInfNorm_le
#check @NumStability.higham8_8_bestRankOneSingularUpdate_exists
#check @NumStability.higham8_8_bestRankOneSingularUpdate_of_maxInverseEntry
#check @NumStability.higham8_8_rankOne_singular_update_abs_eq_inv_abs_inverse_entry
#check @NumStability.higham8_8_rankOne_singular_update_den_eq_zero
#check @NumStability.higham8_8_rankOne_singular_update_iff
#check @NumStability.higham8_9_comparisonMatrix_condAtSolution_eq
#check @NumStability.higham8_9_condAtSolution_le_comparisonMatrix
#check @NumStability.higham8_9_lowerTriangular_condAtSolution_le_comparison_eq
#check @NumStability.higham8_9_upperTriangular_condAtSolution_le_comparison_eq
#check @NumStability.higham8_problem8_9_kahanGram_interlacing
#check @NumStability.higham8_problem8_9_kahan_candidate_hasGramEigenvalue
#check @NumStability.higham8_problem8_9_kahan_candidate_mem_gramEigenvalues
#check @NumStability.higham8_problem8_9_kahan_gram_witness
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_interlacing
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_lower_bound
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_s_eq_one
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_s_eq_zero
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_two
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_zero_three_le
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_zero_two
#check @NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_le_candidate
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_interior_lower_bound
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_interlacing
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_kahanGram_interlacing
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_lower_bound
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_s_eq_one
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_s_eq_zero
#check @NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_two
#check @NumStability.higham8_problem8_9_kahan_witness_forward
#check @NumStability.higham8_problem8_9_kahan_witness_transpose
#check @NumStability.higham8_problem8_9_kahan_zero_one_gramEigenvalues_eq_one
