import NumStability.Analysis.IncreasingPrecision

/-!
# R03 historical-only test — `IncreasingPrecision`

Imports exactly the historical path; checks its preserved public
surface (19 declarations).
-/

#check @NumStability.increasingPrecisionExampleElse_two_precision_failure_of_ieee_finite_stored_inputs_expHat_one
#check @NumStability.increasingPrecisionExampleElse_two_precision_failure_of_ieee_roundToEven_stored_exp_source
#check @NumStability.increasingPrecisionExampleElse_two_precision_failure_of_ieee_roundToEven_stored_source_expHat_one
#check @NumStability.increasingPrecisionExampleY_ieeeDouble_roundToEven_two_thirds
#check @NumStability.increasingPrecisionExampleY_ieeeSingle_roundToEven_two_thirds
#check @NumStability.increasingPrecisionSinExampleSource_ieeeSingle_roundToEven_one
#check @NumStability.increasingPrecisionSinExampleSource_perturbation_lt_one_seventh_binary_grid_error_of_t_le_twenty
#check @NumStability.increasingPrecisionSinExampleSource_perturbation_lt_one_seventh_binary_grid_error_of_t_le_twenty_three
#check @NumStability.increasingPrecision_ieeeDouble_roundToEven_exp_branch_y_eq_one
#check @NumStability.increasingPrecision_ieeeDouble_roundToEven_one_seventh
#check @NumStability.increasingPrecision_ieeeDouble_roundToEven_one_seventh_error
#check @NumStability.increasingPrecision_ieeeDouble_roundToEven_two_thirds
#check @NumStability.increasingPrecision_ieeeSingle_roundToEven_exp_branch_y_eq_one
#check @NumStability.increasingPrecision_ieeeSingle_roundToEven_one_seventh
#check @NumStability.increasingPrecision_ieeeSingle_roundToEven_one_seventh_error
#check @NumStability.increasingPrecision_ieeeSingle_roundToEven_two_thirds
#check @NumStability.increasingPrecision_one_seventh_binary_grid_abs_error_ge
#check @NumStability.increasingPrecision_one_seventh_binary_grid_abs_error_gt_scale_of_t_le_twenty
#check @NumStability.increasingPrecision_one_seventh_binary_grid_abs_error_gt_scale_of_t_le_twenty_three
