import NumStability.Analysis.Problem2_24

/-!
# R03 historical-only test — `Problem2_24`

Imports exactly the historical path; checks its preserved public
surface (27 declarations).
-/

#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_exists_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_later_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_second_or_third_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_third_exact_intermediate_nonfinite
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_third_exact_intermediate_nonfinite_of_finiteSystem_upper_branch
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_third_exact_intermediate_nonfinite_of_one_third_le
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_eq_zero_implies_y3_eq_neg_x_and_exists_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_ne_zero_of_finiteSystem_input
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_eval_ne_zero_of_finiteSystem_intermediates
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_exactExpr_ne_zero_of_finiteSystem
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_finiteSystem_ne_one_third
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_one_third_not_finiteSystem
#check @NumStability.FloatingPointFormat.problem2_24_ieeeDouble_upper_neighbor_le_of_finiteSystem_of_one_third_le
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_exists_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_later_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_second_or_third_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_third_exact_intermediate_nonfinite
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_third_exact_intermediate_nonfinite_of_finiteSystem_upper_branch
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_third_exact_intermediate_nonfinite_of_one_third_le
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_eq_zero_implies_y3_eq_neg_x_and_exists_nonfinite_exact_intermediate
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_ne_zero_of_finiteSystem_input
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_eval_ne_zero_of_finiteSystem_intermediates
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_exactExpr_ne_zero_of_finiteSystem
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_finiteSystem_ne_one_third
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_oneThird_rounds_to_upper
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_one_third_not_finiteSystem
#check @NumStability.FloatingPointFormat.problem2_24_ieeeSingle_upper_neighbor_le_of_finiteSystem_of_one_third_le
