import NumStability.Algorithms.LinearSystems.QR.Householder.StoredQR

/-!
# R11 focused test — `StoredQR`

Exercises the frozen B0003 declaration route into `NumStability.Algorithms.LinearSystems.QR.Householder.StoredQR`
(130 public declarations) and its private-normalized closure
(2 approved private rows).

The private check constructs each mangled `Lean.Name` explicitly, including
the numeric private component via `Name.num`, and requires the P0003
post-delivery name to be present AND the pre-delivery name to be absent.
Requiring the absence is what makes this a normalization test rather than
an existence test.

-/

private def appendNameParts (baseName : Lean.Name) (parts : List String) : Lean.Name :=
  parts.foldl (fun name part => .str name part) baseName

private def mangledPrivateName (moduleName declarationName : String)
    (ordinal : Nat) : Lean.Name :=
  let modulePrefix := appendNameParts .anonymous ("_private" :: moduleName.splitOn ".")
  appendNameParts (.num modulePrefix ordinal) (declarationName.splitOn ".")

/-- The exact P0003-approved post-delivery private names for this destination. -/
private def approvedPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Algorithms.LinearSystems.QR.Householder.StoredQR" "NumStability.ne_zero_of_abs_sub_lt_abs" 0,
  mangledPrivateName "NumStability.Algorithms.LinearSystems.QR.Householder.StoredQR" "NumStability.sum_qrLeadingRow_eq_sum_filter_lt" 0
]

/-- The pre-delivery names the same rows retire; none may survive. -/
private def retiredPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Algorithms.LinearSystems.QR.HouseholderQRSupport" "NumStability.ne_zero_of_abs_sub_lt_abs" 0,
  mangledPrivateName "NumStability.Algorithms.LinearSystems.QR.HouseholderQRSupport" "NumStability.sum_qrLeadingRow_eq_sum_filter_lt" 0
]

run_cmd do
  let environment ← Lean.getEnv
  for name in approvedPrivateNames do
    unless Lean.Environment.contains environment name do
      throwError "R11 private normalization: missing approved name {name}"
  for name in retiredPrivateNames do
    if Lean.Environment.contains environment name then
      throwError "R11 private normalization: retired name {name} still present"

#check @NumStability.coxHigham_exactSignedPivotPanel_sequence_active_block_bound_of_initial_block_bound_of_swapped_active_max_pivot_of_leading_block_det_ne_zero
#check @NumStability.dim_mul_budget_sq_lt_trailingNorm2Sq_of_leadingBlock_leftInverse_frobNorm_budget
#check @NumStability.dim_mul_budget_sq_lt_trailingNorm2Sq_of_leadingBlock_leftInverse_infNorm_budget
#check @NumStability.dim_mul_budget_sq_lt_trailingNorm2Sq_of_leadingBlock_leftInverse_row_norm_budget
#check @NumStability.dim_mul_budget_sq_lt_trailingNorm2Sq_of_leading_dual_norm_budget
#check @NumStability.exact_trailing_householder_sequence_lower_zero
#check @NumStability.exists_active_trailing_entry_ne_of_column_notInPreviousSpan
#check @NumStability.exists_active_trailing_entry_ne_of_leading_block_det_ne_zero
#check @NumStability.exists_active_trailing_entry_ne_of_leading_block_leftInverses
#check @NumStability.exists_active_trailing_entry_ne_of_leading_witnesses
#check @NumStability.fl_householderApplyCompactPanel_eq_applyMatrixRect
#check @NumStability.fl_householderApplyCompactPanel_rect_orthogonal_columnwise_vector_sequence_geometric
#check @NumStability.fl_householderStoredPanelStep_eq_applyMatrixRect_of_active_not_below
#check @NumStability.fl_householderStoredPanel_sequence_completed_column_eq_pivot_succ
#check @NumStability.fl_householderStoredPanel_sequence_diag_nonzero_of_step_diag_nonzero
#check @NumStability.fl_householderStoredPanel_sequence_leadingBlock_offdiag_budget_of_exact_stage_budgets_factor
#check @NumStability.fl_householderStoredPanel_sequence_leadingBlock_offdiag_budget_of_signed_stage_budgets_factor
#check @NumStability.fl_householderStoredPanel_sequence_lower_zero
#check @NumStability.fl_householderStoredPanel_sequence_prefixSpan_of_leftInverse_previousLeadingBlockTranspose
#check @NumStability.fl_householderStoredPanel_sequence_prefix_diag_nonzero_of_step_diag_nonzero
#check @NumStability.fl_householderStoredPanel_sequence_prefix_lower_zero
#check @NumStability.fl_householderStoredPanel_sequence_topBlock_shape_facts
#check @NumStability.fl_householderStoredTrailingPanelStep_HouseholderColumnwisePanelAppError_of_budget
#check @NumStability.fl_householderStoredTrailingPanelStep_diag_nonzero_of_budget_lt_abs_alpha
#check @NumStability.fl_householderStoredTrailingPanel_higham_columnwise_factorization
#check @NumStability.fl_householderStoredTrailingPanel_rect_orthogonal_columnwise_vector_sequence_geometric
#check @NumStability.fl_householderStoredTrailingPanel_sequence_current_pivot_ne_zero_of_leadingBlock_det_ne_zero
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_budget_lt_abs_alpha
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_leading_block_det_ne_zero_sqrt_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_leading_block_leftInverses_sqrt_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_leading_witnesses_sqrt_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_pivot_ne_alpha
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_signed_alpha_trailingNorm_pos_sqrt_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_active_entry_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_leadingBlock_leftInverse_frobNorm_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_leadingBlock_leftInverse_infNorm_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_leadingBlock_leftInverse_norm_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_leading_dual_norm_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_sqrt_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_span_nonbreakdown_trailingNorm2Sq_budget
#check @NumStability.fl_householderStoredTrailingPanel_sequence_diag_nonzero_of_trailingNorm_pos_mul_nonpos
#check @NumStability.fl_householderStoredTrailingPanel_sequence_prefix_diag_nonzero_of_signed_alpha_trailingNorm_pos_sqrt_budget
#check @NumStability.householderActiveBlockNorm2Sq_pos_of_column_notInPreviousSpan
#check @NumStability.householderActiveBlockNorm2Sq_pos_of_leading_block_det_ne_zero
#check @NumStability.householderActiveBlockNorm2Sq_pos_of_leading_block_leftInverses
#check @NumStability.householderActiveBlockNorm2Sq_pos_of_leading_witnesses
#check @NumStability.householderActiveBlockNorm2Sq_pos_sequence_of_leading_block_det_ne_zero
#check @NumStability.householderColumnwisePanelAppError_rect_orthogonal_columnwise_vector_sequence_geometric
#check @NumStability.householderPanelAppError_rect_orthogonal_matrix_vector_sequence_geometric
#check @NumStability.householderTrailingNorm2Sq_ge_inv_leadingBlock_leftInverse_frobNorm_budget
#check @NumStability.householderTrailingNorm2Sq_ge_inv_leadingBlock_leftInverse_infNorm_budget
#check @NumStability.householderTrailingNorm2Sq_ge_inv_leadingBlock_leftInverse_row_norm_budget
#check @NumStability.householderTrailingNorm2Sq_ge_inv_leading_dual_norm_budget
#check @NumStability.householderTrailingNorm2Sq_pos_of_column_notInPreviousSpan
#check @NumStability.householderTrailingNorm2Sq_pos_of_leading_block_det_ne_zero
#check @NumStability.householderTrailingNorm2Sq_pos_of_leading_block_leftInverses
#check @NumStability.householderTrailingNorm2Sq_pos_of_leading_witnesses
#check @NumStability.not_forall_det_ne_zero_implies_all_leading_blocks_det_ne_zero
#check @NumStability.not_forall_det_ne_zero_implies_first_pivot_ne_zero
#check @NumStability.orthogonal_vector_sequence_geometric
#check @NumStability.orthogonal_vector_sequence_one_step
#check @NumStability.orthogonal_vector_sequence_one_step_fixedQ
#check @NumStability.qrColumnNotInPreviousSpan
#check @NumStability.qrColumnNotInPreviousSpan_of_leadingColumnLeftInverse
#check @NumStability.qrLeadingBlock
#check @NumStability.qrLeadingBlock_current_pivot_ne_zero_of_local_upper_triangular_det_ne_zero
#check @NumStability.qrLeadingBlock_det_ne_zero_of_local_upper_triangular_diag_ne_zero
#check @NumStability.qrLeadingBlock_det_ne_zero_of_upper_triangular_diag_ne_zero
#check @NumStability.qrLeadingColumn
#check @NumStability.qrLeadingColumnLeftInverse
#check @NumStability.qrLeadingColumnLeftInverse_of_det_ne_zero_leadingBlock
#check @NumStability.qrLeadingColumnLeftInverse_of_leftInverse_leadingBlock
#check @NumStability.qrLeadingColumnLeftInverse_padded_row_norm_sq_eq
#check @NumStability.qrLeadingOffdiagStop
#check @NumStability.qrLeadingOffdiagStop_le
#check @NumStability.qrLeadingRow
#check @NumStability.qrPivotCounterexample2
#check @NumStability.qrPivotCounterexample2_det_ne_zero
#check @NumStability.qrPivotCounterexample2_first_leadingBlock_det_zero
#check @NumStability.qrPivotCounterexample2_first_pivot_zero
#check @NumStability.qrPrefixBasisCoefficientMatrix
#check @NumStability.qrPrefixBasisCoefficientMatrix_of_det_ne_zero_previousLeadingBlockTranspose
#check @NumStability.qrPrefixBasisCoefficientMatrix_of_leftInverse_previousLeadingBlockTranspose
#check @NumStability.qrPrefixRow
#check @NumStability.qrPrefixSupportSpannedByPreviousColumns
#check @NumStability.qrPrefixSupportSpannedByPreviousColumns_of_det_ne_zero_previousLeadingBlockTranspose
#check @NumStability.qrPrefixSupportSpannedByPreviousColumns_of_leadingBlock_upper_det_ne_zero
#check @NumStability.qrPrefixSupportSpannedByPreviousColumns_of_leftInverse_previousLeadingBlockTranspose
#check @NumStability.qrPrefixSupportSpannedByPreviousColumns_of_prefixBasisCoefficientMatrix
#check @NumStability.qrPreviousColumn
#check @NumStability.qrPreviousLeadingBlockTranspose
#check @NumStability.qrPreviousLeadingBlockTranspose_det_ne_zero_of_local_lower_triangular_diag_ne_zero
#check @NumStability.qrPreviousLeadingBlockTranspose_det_ne_zero_of_upper_triangular_diag_ne_zero
#check @NumStability.rect_orthogonal_columnwise_vector_sequence_geometric
#check @NumStability.rect_orthogonal_matrix_vector_sequence_geometric
#check @NumStability.rect_orthogonal_matrix_vector_sequence_one_step
#check @NumStability.rect_orthogonal_sequence_geometric
#check @NumStability.rect_orthogonal_sequence_one_step
#check @NumStability.rectangular_topBlock_shape_facts_of_lower_zero
#check @NumStability.storedQRCompactPivotBudget_le_sequence_column_norm
#check @NumStability.storedQRCompactSequenceRelativeBudget
#check @NumStability.storedQRCompactSequenceRelativeBudget_column_bound
#check @NumStability.storedQRCompactSequenceRelativeBudget_le_mul_of_step_le
#check @NumStability.storedQRCompactSequenceRelativeBudget_nonneg
#check @NumStability.storedQRCompactSequenceRelativeBudget_rhs_bound
#check @NumStability.storedQRCompactStepNormBudgetCoeff
#check @NumStability.storedQRCompactStepNormBudgetCoeff_le_of_abs_beta_norm_sq_le
#check @NumStability.storedQRCompactStepNormBudgetCoeff_le_of_den_ne_zero
#check @NumStability.storedQRCompactStepNormBudgetCoeff_le_of_forall_abs_beta_norm_sq_le
#check @NumStability.storedQRCompactStepNormBudgetCoeff_le_of_forall_den_ne_zero
#check @NumStability.storedQRCompactStepNormBudgetCoeff_le_of_forall_source_den_ne_zero
#check @NumStability.storedQRCompactStepNormBudgetCoeff_nonneg
#check @NumStability.storedQRCompactStepRelativeBudget
#check @NumStability.storedQRCompactStepRelativeBudget_le_gamma_of_source_den_ne_zero_operation_count
#check @NumStability.storedQRCompactStepRelativeBudget_le_mul_add_normBudgetCoeff
#check @NumStability.storedQRCompactStepRelativeBudget_le_mul_add_of_column_rhs_le
#check @NumStability.storedQRCompactStepRelativeBudget_le_mul_add_of_componentBudget_le_mul_abs
#check @NumStability.storedQRCompactStepRelativeBudget_le_mul_add_of_normBudget_le_mul
#check @NumStability.storedQRCompactStepRelativeBudget_le_sequence
#check @NumStability.storedQRCompactStepRelativeBudget_nonneg
#check @NumStability.storedQRSignedStageBeta
#check @NumStability.storedQRSignedStageVector
#check @NumStability.storedQRSignedStage_abs_beta_norm_sq_eq_two_of_den_ne_zero
#check @NumStability.storedQRSignedStage_abs_beta_norm_sq_le_two_of_den_ne_zero
#check @NumStability.storedQRSignedStage_completed_column_preservation
#check @NumStability.storedQRSignedStage_exact_same_reflector_bound_of_prefix_or_active_stage_bounds
#check @NumStability.storedQRSignedStage_pivot_column_zero_below_of_trailingNorm_pos
#check @NumStability.storedQRSignedStage_pivot_zeroing_field_of_normSqBudget
#check @NumStability.storedQRSignedStage_pivot_zeroing_field_of_trailingNorm_pos
#check @NumStability.vecNorm2Sq_qrLeadingRow_padded_eq
