import NumStability.Algorithms.StationaryIteration

/-!
# R01 historical-only import test O01

Imports exactly the historical owner `NumStability.Algorithms.StationaryIteration` and checks its complete preserved public surface.
-/

#check NumStability.finiteResidualSigma_le_diagonalizable_bound
#check NumStability.finiteResidualSigma_le_diagonalizable_max_bound
#check NumStability.residualSigmaSup_le_diagonalizable_max_bound
#check NumStability.residualSigmaTsum_le_diagonalizable_bound
#check NumStability.residualSigmaTsum_le_diagonalizable_max_bound_direct
#check NumStability.sigma_bound
#check NumStability.singularErrorSourceTerm_componentwise_bound
#check NumStability.singularErrorSourceTerm_componentwise_bound_of_local_error
#check NumStability.singularErrorSourceTerm_norm_bound
#check NumStability.singularErrorSourceTerm_norm_bound_of_local_error
#check NumStability.singular_error_split_finite_of_indexOneDrazin_projector
#check NumStability.stationaryDrazinFixedProjector_fixed_by_G
#check NumStability.stationaryDrazinFixedProjector_idempotent
#check NumStability.stationaryDrazinFixedProjector_matMulVec_fixed
#check NumStability.stationaryDrazinFixedProjector_matPow_fixed
#check NumStability.stationaryDrazinRangeProjector_commutes_with_G
#check NumStability.stationaryDrazinRangeProjector_commutes_with_matPow
#check NumStability.stationaryDrazinRangeProjector_matPow_sandwich
#check NumStability.stationaryDrazinRangeProjector_null_component_fixed
#check NumStability.stationaryDrazin_matPow_vec_split
#check NumStability.stationaryDrazin_matPow_vec_tendsto_fixedProjector_of_range_tendsto_zero
