import NumStability.Analysis.LinearOperators.MatrixPowers.Henrici.DepartureFromNormality
import NumStability.Analysis.LinearOperators.MatrixPowers.Henrici.Extremal
import NumStability.Analysis.LinearOperators.MatrixPowers.Henrici.ImprovedConstant
import NumStability.Analysis.LinearOperators.MatrixPowers.Henrici.SharpConstant

#check NumStability.centered_sq_eq_exactSharp
