import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.ShiftedHessenbergSolvability

#check NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_and_HessenbergGEPPUTrace_growth_of_realSchur_upperHessenberg_triangular_no_common_complex_right_eigenvalue
