import NumStability.Analysis.RealInvariantSubspace

#check NumStability.RealInvariantSubspaceAux.cplx
#check NumStability.exists_real_invariant_subspace_dim_le_two
#check NumStability.MatrixNoRealEigenline
