import NumStability.Algorithms.Cholesky.CholeskyFl
import NumStability.Algorithms.Cholesky.CholeskyNonsym
import NumStability.Algorithms.Cholesky.CholeskySpec
import NumStability.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.KahanTelescope.Identity
import NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds
import NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.OperatorNorm.SourceBound
import NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.UnboundedGrowth.Construction
import NumStability.Source.Higham.Chapter10.Problem01.PositiveSemidefiniteEntries.EntryBounds.Results
import NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.ConstructiveFactorization.Existence
import NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.PivotingAndScaling.Results
import NumStability.Source.Higham.Chapter10.Theorem07.Core.Results
import NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound
import NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds
import NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.SchurPerturbation.Family

/-!
# R04 approved private normalization (exhaustive)

Constructs all 115 approved post-delivery private names (including
the 14 identity rows) and requires each present in the environment, and each
of the 101 nonidentity pre-delivery names absent.
-/

private def appendNameParts (baseName : Lean.Name) (parts : List String) : Lean.Name :=
  parts.foldl (fun name part => .str name part) baseName

private def mangledPrivateName (moduleName declarationName : String)
    (ordinal : Nat) : Lean.Name :=
  let modulePrefix := appendNameParts .anonymous ("_private" :: moduleName.splitOn ".")
  appendNameParts (.num modulePrefix ordinal) (declarationName.splitOn ".")

private def approvedPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_borderedRealMatrix" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_bordered_inverse_energy_lt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexBlockSchur_re_im_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexEnergy_im_fintype" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexEnergy_re_fintype" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterA" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterB" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterB_spd" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterC" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterC_spd" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounterFP" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_L10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_U00" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_U10" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_gamma" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_gammaValid" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexGammaCounter_radius_lower_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complexVector_re_or_im_nonzero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_U_entry_eq_leading_schur" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_borderedMinor_eq_pivots_mul_U" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_borderedU_det" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_inverse_eq_X_minus_iY" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_leadingRows_mul_of_lower_left" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_complex_leading_det_eq_prod_U_diag" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_imag_schur_scalar_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_input_complexMaxEntryNorm_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseX" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseX_energy_two_lt_border" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseX_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseY" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseY_energy_two_lt_border" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseY_eq_swappedX" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverseY_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverse_real_part_upper" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_inverse_split_equations" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_matrixPosDef_to_isSymPosDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_posDef_entry_sq_le_diag_mul_diag" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_posDef_inverse_anti" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_principal_border_at_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_principal_border_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_realQuadForm_nonneg_of_spd" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_real_schur_scalar_pos" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_sourceDiagonalRep_norm_lt_three_max" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_sourceSchurDiagonalRep_of_leading" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_sourceUpperEntryRep_norm_lt_three_max" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_sourceUpperEntryRep_of_exactLU" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_symmetric_cross_sum_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_symmetric_cross_sum_sub_eq_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_symmetric_cross_sum_sub_eq_zero_fintype" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_symmetric_mulVec_cross_eq" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_symmetric_mulVec_cross_eq_fintype" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.NoPivotLU.SourceBounds" "NumStability.higham10_30_twoTrailingPrincipal_posDef" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.OperatorNorm.SourceBound" "NumStability.complexMatrixOp2_vecMulVec" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.OperatorNorm.SourceBound" "NumStability.higham10Kahan_geometric_segment" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_absMatrix_symmetric_of_symmetric" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_matSub_id_symmetric" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_one_sub_le_recip_sub_abs" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_recip_abs_le_one_add_gap" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_resolvent_commutes" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.NormalizedResolvent.SourceBound" "NumStability.higham10_8_right_resolvent_majorant_id" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.ConstructiveFactorization.Existence" "NumStability.psd_diag_nonneg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.ConstructiveFactorization.Existence" "NumStability.psd_zero_diag_row_zero" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Problem01.PositiveSemidefiniteEntries.EntryBounds.Results" "NumStability.quadForm_two_point" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.ConstructiveFactorization.Existence" "NumStability.sum_filter_succ_tail" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.SchurPerturbation.Family" "NumStability.higham10_14_abs_entry_le_of_rectOpNorm2Le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.SchurPerturbation.Family" "NumStability.higham10_14_rectOpNorm2Le_add" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.SchurPerturbation.Family" "NumStability.higham10_14_rectOpNorm2Le_neg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_cert_core" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_entry_bound" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_opNorm2Le_neg" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_sqrt_nat_le_nat" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_sum_truncate_at" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_trunc_abs_gram" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_trunc_abs_gram_computed" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RankSensitiveError.Bounds" "NumStability.higham10_14_zeroRowPad_opNorm2Le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.UnboundedGrowth.Construction" "NumStability.higham10_18_row_cast" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Lemma13.KahanSharpness.UnboundedGrowth.Construction" "NumStability.higham10_18_row_nat" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Section03.PositiveSemidefinite.PivotingAndScaling.Results" "NumStability.higham10_9_upper_product_sum_split" 0,
  mangledPrivateName "NumStability.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.KahanTelescope.Identity" "NumStability.kahan_telescope" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.bordered_perturbation_floor_sqrt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.solved_border_mass_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceB" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceC" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceD" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceD_pos_of_gamma_lt_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceE" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceI" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceP" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceP_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceP_sub_B_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceP_sub_B_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceQ" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceQ_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.sourceR" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_boundary_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_common_coefficients" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_common_product_core" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_product_diff_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_product_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_stage_interior_coeff_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07.Core.Results" "NumStability.source_stage_recip_le" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.chol_cert_core" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.chol_term_factor_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.counter_one" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.counter_plain_prod" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.fl_cholesky_entry_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.one_add_pos_of_abs_le_u" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.suffix_mul_prefix_eq_prod" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.sum_truncate_at" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyFl" "NumStability.u_lt_one_of_gammaValid_succ" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyNonsym" "NumStability.sum_zero_off_lt" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskySpec" "NumStability.cholesky_factor_uniqueness" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskySpec" "NumStability.schur_pd" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskySpec" "NumStability.schur_sym" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskySpec" "NumStability.spd_diag_pos" 0
]

private def retiredPrivateNames : List Lean.Name := [
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_borderedRealMatrix" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_bordered_inverse_energy_lt" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexBlockSchur_re_im_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexEnergy_im_fintype" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexEnergy_re_fintype" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterA" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterB" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterB_spd" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterC" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterC_spd" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounterFP" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_L10" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_U00" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_U10" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_gamma" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_gammaValid" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexGammaCounter_radius_lower_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complexVector_re_or_im_nonzero" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_U_entry_eq_leading_schur" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_borderedMinor_eq_pivots_mul_U" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_borderedU_det" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_inverse_eq_X_minus_iY" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_leadingRows_mul_of_lower_left" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_complex_leading_det_eq_prod_U_diag" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_imag_schur_scalar_pos" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_input_complexMaxEntryNorm_pos" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseX" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseX_energy_two_lt_border" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseX_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseY" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseY_energy_two_lt_border" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseY_eq_swappedX" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverseY_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverse_real_part_upper" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_inverse_split_equations" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_matrixPosDef_to_isSymPosDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_posDef_entry_sq_le_diag_mul_diag" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_posDef_inverse_anti" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_principal_border_at_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_principal_border_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_realQuadForm_nonneg_of_spd" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_real_schur_scalar_pos" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_sourceDiagonalRep_norm_lt_three_max" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_sourceSchurDiagonalRep_of_leading" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_sourceUpperEntryRep_norm_lt_three_max" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_sourceUpperEntryRep_of_exactLU" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_symmetric_cross_sum_eq" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_symmetric_cross_sum_sub_eq_zero" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_symmetric_cross_sum_sub_eq_zero_fintype" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_symmetric_mulVec_cross_eq" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_symmetric_mulVec_cross_eq_fintype" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10ComplexPositiveDefiniteSourceClosure" "NumStability.higham10_30_twoTrailingPrincipal_posDef" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10KahanSharpnessSource" "NumStability.complexMatrixOp2_vecMulVec" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10KahanSharpnessSource" "NumStability.higham10Kahan_geometric_segment" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_absMatrix_symmetric_of_symmetric" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_matSub_id_symmetric" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_one_sub_le_recip_sub_abs" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_recip_abs_le_one_add_gap" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_resolvent_commutes" 0,
  mangledPrivateName "NumStability.Algorithms.Ch10Theorem108Componentwise" "NumStability.higham10_8_right_resolvent_majorant_id" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyPSD" "NumStability.psd_diag_nonneg" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyPSD" "NumStability.psd_zero_diag_row_zero" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyPSD" "NumStability.quadForm_two_point" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.CholeskyPSD" "NumStability.sum_filter_succ_tail" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014Equation1022" "NumStability.higham10_14_abs_entry_le_of_rectOpNorm2Le" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014Equation1022" "NumStability.higham10_14_rectOpNorm2Le_add" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014Equation1022" "NumStability.higham10_14_rectOpNorm2Le_neg" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_cert_core" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_entry_bound" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_opNorm2Le_neg" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_sqrt_nat_le_nat" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_sum_truncate_at" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_trunc_abs_gram" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_trunc_abs_gram_computed" 0,
  mangledPrivateName "NumStability.Algorithms.Cholesky.Higham1014SourceError" "NumStability.higham10_14_zeroRowPad_opNorm2Le" 0,
  mangledPrivateName "NumStability.Algorithms.HighamChapter10" "NumStability.higham10_18_row_cast" 0,
  mangledPrivateName "NumStability.Algorithms.HighamChapter10" "NumStability.higham10_18_row_nat" 0,
  mangledPrivateName "NumStability.Algorithms.HighamChapter10" "NumStability.higham10_9_upper_product_sum_split" 0,
  mangledPrivateName "NumStability.Algorithms.HighamChapter10" "NumStability.kahan_telescope" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.bordered_perturbation_floor_sqrt" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.solved_border_mass_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceB" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceC" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceD" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceD_pos_of_gamma_lt_one" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceE" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceI" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceP" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceP_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceP_sub_B_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceP_sub_B_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceQ" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceQ_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.sourceR" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_boundary_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_common_coefficients" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_common_product_core" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_product_diff_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_product_two_formula" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_stage_interior_coeff_le" 0,
  mangledPrivateName "NumStability.Source.Higham.Chapter10.Theorem07" "NumStability.source_stage_recip_le" 0
]

run_cmd do
  let environment ← Lean.getEnv
  for name in approvedPrivateNames do
    unless Lean.Environment.contains environment name do
      throwError "R04 private normalization: missing approved name {name}"
  for name in retiredPrivateNames do
    if Lean.Environment.contains environment name then
      throwError "R04 private normalization: retired name {name} still present"
