import Mathlib.Analysis.InnerProductSpace.PiL2
import NumStability.Algorithms.LinearSystems.LeastSquares.Basic
import NumStability.Algorithms.LinearSystems.LeastSquares.NormalEquations
import NumStability.Algorithms.LinearSystems.LeastSquares.StoredQR
import NumStability.Algorithms.RandNLA.RowSamplingLeverage
import NumStability.Algorithms.RandNLA.RowSamplingLeverageMGF
import NumStability.Algorithms.RandomizedLinearAlgebra.LeastSquaresSketching.Objectives.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.LeastSquaresSketching.RowSampling.Core
import NumStability.Analysis.FiniteProbability
import NumStability.Analysis.MatrixAlgebra
import NumStability.Analysis.Perturbation.LeastSquares.BackwardError
import NumStability.Analysis.Perturbation.LeastSquares.Basic
import NumStability.Analysis.Perturbation.LeastSquares.NormalEquations
import NumStability.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.Endpoints
import NumStability.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.FloatingPointObjectiveBounds
import NumStability.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.SketchedObjectiveBounds
import NumStability.Source.Higham.Chapter20.Theorem03.QRSolve

/-!
Historical owner retained as an import-only compatibility wrapper; its declarations were relocated under the R09/R10 completion waves per the reviewed route ledger.
-/
