import NumStability.Algorithms

/-!
# Algorithms entry-point smoke test

Checks representative arithmetic, factorization, and randomized-linear-
algebra declarations through the historical Algorithms aggregate.
-/

#check NumStability.fl_recursiveSum
#check NumStability.fl_noGuardDotProduct
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.fl_pairwiseSumSixDisplayed
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25NewtonEquation
#check NumStability.OrthogonalSequenceBackwardError
#check NumStability.RectRankFactorization
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.HighamChapter4KaoWang.higham43_computedBudget_ne_kaoWangExactCost_witness
#check NumStability.higham17_problem17_1
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.higham12_problem12_2_two_step_recurrence
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.blockMaxNorm
#check NumStability.IsBlockDiagDomCol
#check NumStability.BlockLUFactSpec
#check NumStability.BlockLUBackwardError
#check NumStability.MatMulFirstOrderSpec
#check NumStability.growthFactorEntry_sq_kappa_budget_le_of_growth_le_inv_ratio
#check NumStability.blockMatrixNonsingular_of_posDef_flat
#check NumStability.higham13_maxNorm_vecResidual_lift
#check NumStability.blockSchur
#check NumStability.block_lu_one_step
#check NumStability.dhsBlockForwardConventionalSolution
#check NumStability.Ch22B.ch22bComplexConfluent_theorem12_3_exact_q_bound
#check NumStability.higham27_problem27_6_cubic_error_bound
#check NumStability.StrassenRecurrence
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_theorem23_2_strassen_closedCoefficient_firstOrder
#check NumStability.higham23_theorem23_3_winograd_closedCoefficient_firstOrder
#check NumStability.higham23_eq23_11_miller_normwise
#check NumStability.higham23_biniLotti_scaledRemainder_isBigO_u_sq
#check NumStability.higham23_threeMStrassen_sourceCoefficient
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham26ADCrudeSweep_nondecreasing
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.higham14SchulzStep
#check NumStability.Ch14Ext.ch14ext_schulzIter_tendsto_inverse_of_lt_two_div_norm_sq
#check NumStability.ch14ext_problem14_13_gej_bound_fin_one
#check NumStability.Ch14Ext.ch14ext_hyman_flDet_backward_error_original
#check NumStability.higham21Cond2With_row_scaling
#check NumStability.Ch14Ext.ch14ext_singularValue_abs_sub_le_of_euclideanLin_diff_bound
#check NumStability.Ch14Ext.ch14ext_problem14_15_det_add_rel_le_of_kappa2_opNorm2_inv_card_guard
#check NumStability.higham21_theorem21_4_computed_qhat_omegaR_le_gamma
#check NumStability.higham28NormalizedHilbertDet_tendsto_atTop
#check NumStability.higham28_not_HilbertDetAsymptotic
#check NumStability.integral_abs_standardGaussian_difference
#check MeasureTheory.measure_eq_of_invariant_probability_of_pretransitive
#check NumStability.Lemma66.lemma66_c_op2_le
#check NumStability.ch6aside_conditionF_ge_sqrt_n
#check NumStability.ch6aside_blockAntidiag_lp_eq

#check NumStability.activeBlockIndices13_8
#check NumStability.Algorithm13_3Implementation1LocalSpec
#check NumStability.block_diag_dom_growth_bound_step
#check NumStability.block_diag_dom_schur_inherit
#check NumStability.block_lu_solve_backward_error
#check NumStability.BlockLUFactSpec.eq_of_schurTail_unique_of_right_inverse
#check NumStability.growthFactorEntry_blockMatrixFirstSplitFlat_eq_blockMatrixFlatFin
#check NumStability.higham13_algorithm13_3_firstSplitStageHistoryGrowthFactor_le_two_of_product_bound_diag_update
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa
#check NumStability.higham13_lemma13_10_conditional_bound
