import NumStability.Source.Higham.Chapter16.QuasiRounded.Sylvester

/-!
# R06 canonical-only test — `Sylvester`

Imports exactly the canonical destination and checks all 16
routed public declarations. No historical owner import.
-/

#check @NumStability.Wave15.H16_eq16_7_8_quasi_sylvesterVecCoeff_blockBackSub_componentwise_error_and_residual
#check @NumStability.Wave15.H16_eq16_7_8_quasi_sylvesterVecCoeff_blockBackSub_componentwise_error_and_residual_with_growthTerm
#check @NumStability.Wave15.H16_eq16_7_quasi_sylvesterVecCoeff_blockBackSub_backward_error
#check @NumStability.Wave15.H16_eq16_7_quasi_sylvesterVecCoeff_blockBackSub_backward_error_componentwise
#check @NumStability.Wave15.H16_eq16_8_quasi_sylvesterResidualRect_blockBackSub_componentwise_le
#check @NumStability.Wave15.H16_eq16_8_quasi_sylvesterResidualRect_blockBackSub_componentwise_le_with_growthTerm
#check @NumStability.Wave15.H16_eq16_8_quasi_sylvesterVecCoeff_blockBackSub_componentwise_residual
#check @NumStability.Wave15.H16_eq16_8_quasi_sylvesterVecCoeff_blockBackSub_componentwise_residual_with_growthTerm
#check @NumStability.Wave15.sylvesterResidualRect_quasiTriangular_blockBackSub_componentwise_le
#check @NumStability.Wave15.sylvesterResidualRect_quasiTriangular_blockBackSub_componentwise_le_with_growthTerm
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_backward_error
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_backward_error_componentwise
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_componentwise_error_and_residual
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_componentwise_error_and_residual_with_growthTerm
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_componentwise_residual
#check @NumStability.Wave15.sylvesterVecCoeff_quasiTriangular_blockBackSub_componentwise_residual_with_growthTerm
