import NumStability.Source.Higham.Chapter11.BunchKaufman.Rounded.TerminalClosedForm

/-!
# R06 canonical-only test — `TerminalClosedForm`

Imports exactly the canonical destination and checks all 11
routed public declarations. No historical owner import.
-/

#check @NumStability.Higham11RoundedBunchKaufmanExecution.completed_of_middleSolveRunDomain
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_dimension
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_source_dimension
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_source_firstOrder
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_source_maxEntryNorm
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_source_polynomial
#check @NumStability.Higham11RoundedBunchKaufmanExecution.dimensionResidualCoefficient
#check @NumStability.Higham11RoundedBunchKaufmanExecution.dimensionResidualCoefficient_le_twoHundredSixteen_mul_dimension_mul_u
#check @NumStability.Higham11RoundedBunchKaufmanExecution.finiteResidualCoefficient_le_dimensionResidualCoefficient
#check @NumStability.Higham11RoundedBunchKaufmanExecution.one_le_roundedGrowthFactor_at_sourceMax
#check @NumStability.Higham11RoundedBunchKaufmanExecution.solveResidualCoefficient_thirtySix_mul_u_le_linear_add_quadratic
