import NumStability.Algorithms.PNormPowerMethod

/-!
# Old path: `NumStability.Algorithms.PNormPowerMethod`

Imports only the historical module. Every public declaration the owner
had at C0007 still resolves through the compatibility module, so no
consumer that used this import path can have been broken by the split.
-/

#check @NumStability.Ch15.HasDirectionalGradientAt
#check @NumStability.Ch15.IsSubgradient
#check @NumStability.Ch15.PNormPair
#check @NumStability.Ch15.PNormPair.A
#check @NumStability.Ch15.PNormPair.State
#check @NumStability.Ch15.PNormPair.State.casesOn
#check @NumStability.Ch15.PNormPair.State.ctorIdx
#check @NumStability.Ch15.PNormPair.State.mk
#check @NumStability.Ch15.PNormPair.State.mk.inj
#check @NumStability.Ch15.PNormPair.State.mk.injEq
#check @NumStability.Ch15.PNormPair.State.mk.noConfusion
#check @NumStability.Ch15.PNormPair.State.mk.sizeOf_spec
#check @NumStability.Ch15.PNormPair.State.noConfusion
#check @NumStability.Ch15.PNormPair.State.noConfusionType
#check @NumStability.Ch15.PNormPair.State.rec
#check @NumStability.Ch15.PNormPair.State.recOn
#check @NumStability.Ch15.PNormPair.State.x
#check @NumStability.Ch15.PNormPair.State.γ
#check @NumStability.Ch15.PNormPair.casesOn
#check @NumStability.Ch15.PNormPair.convergence_test_iff
#check @NumStability.Ch15.PNormPair.ctorIdx
#check @NumStability.Ch15.PNormPair.dp
#check @NumStability.Ch15.PNormPair.dp_attains
#check @NumStability.Ch15.PNormPair.dp_isSubgradient
#check @NumStability.Ch15.PNormPair.dp_qunit
#check @NumStability.Ch15.PNormPair.dq
#check @NumStability.Ch15.PNormPair.dq_attains
#check @NumStability.Ch15.PNormPair.dq_punit
#check @NumStability.Ch15.PNormPair.eq15_2_zof_isSubgradient
#check @NumStability.Ch15.PNormPair.eq15_5_subgradient_inequality
#check @NumStability.Ch15.PNormPair.gammaSeq
#check @NumStability.Ch15.PNormPair.gammaSeq_ge_start
#check @NumStability.Ch15.PNormPair.gammaSeq_le_opP
#check @NumStability.Ch15.PNormPair.gammaSeq_mono
#check @NumStability.Ch15.PNormPair.holder
#check @NumStability.Ch15.PNormPair.lemma152a
#check @NumStability.Ch15.PNormPair.lemma152b
#check @NumStability.Ch15.PNormPair.mk
#check @NumStability.Ch15.PNormPair.mk.inj
#check @NumStability.Ch15.PNormPair.mk.injEq
#check @NumStability.Ch15.PNormPair.mk.noConfusion
#check @NumStability.Ch15.PNormPair.mk.sizeOf_spec
#check @NumStability.Ch15.PNormPair.noConfusion
#check @NumStability.Ch15.PNormPair.noConfusionType
#check @NumStability.Ch15.PNormPair.opP
#check @NumStability.Ch15.PNormPair.op_bound
#check @NumStability.Ch15.PNormPair.pN
#check @NumStability.Ch15.PNormPair.pN_nonneg
#check @NumStability.Ch15.PNormPair.powerStep
#check @NumStability.Ch15.PNormPair.powerStep_gamma_eq
#check @NumStability.Ch15.PNormPair.powerStep_gamma_le_opP
#check @NumStability.Ch15.PNormPair.powerStep_scaling
#check @NumStability.Ch15.PNormPair.qN
#check @NumStability.Ch15.PNormPair.rec
#check @NumStability.Ch15.PNormPair.recOn
#check @NumStability.Ch15.PNormPair.xnext
#check @NumStability.Ch15.PNormPair.xseq
#check @NumStability.Ch15.PNormPair.xseq_punit
#check @NumStability.Ch15.PNormPair.yof
#check @NumStability.Ch15.PNormPair.yof_sub
#check @NumStability.Ch15.PNormPair.z_dot
#check @NumStability.Ch15.PNormPair.zof
#check @NumStability.Ch15.SmoothPNormPair
#check @NumStability.Ch15.SmoothPNormPair.P
#check @NumStability.Ch15.SmoothPNormPair.casesOn
#check @NumStability.Ch15.SmoothPNormPair.composite_hasDirectionalGradientAt
#check @NumStability.Ch15.SmoothPNormPair.conjugate
#check @NumStability.Ch15.SmoothPNormPair.ctorIdx
#check @NumStability.Ch15.SmoothPNormPair.dp_qnorm_one
#check @NumStability.Ch15.SmoothPNormPair.eq15_2_subdifferential_singleton
#check @NumStability.Ch15.SmoothPNormPair.eq15_3_F
#check @NumStability.Ch15.SmoothPNormPair.eq15_3_directional
#check @NumStability.Ch15.SmoothPNormPair.eq15_3_directional_of_full_rank
#check @NumStability.Ch15.SmoothPNormPair.eq15_3_gradient
#check @NumStability.Ch15.SmoothPNormPair.eq15_5_subgradient_inequality
#check @NumStability.Ch15.SmoothPNormPair.mk
#check @NumStability.Ch15.SmoothPNormPair.mk.inj
#check @NumStability.Ch15.SmoothPNormPair.mk.injEq
#check @NumStability.Ch15.SmoothPNormPair.mk.noConfusion
#check @NumStability.Ch15.SmoothPNormPair.mk.sizeOf_spec
#check @NumStability.Ch15.SmoothPNormPair.noConfusion
#check @NumStability.Ch15.SmoothPNormPair.noConfusionType
#check @NumStability.Ch15.SmoothPNormPair.one_lt_p
#check @NumStability.Ch15.SmoothPNormPair.one_lt_q
#check @NumStability.Ch15.SmoothPNormPair.p
#check @NumStability.Ch15.SmoothPNormPair.pN_gradient
#check @NumStability.Ch15.SmoothPNormPair.pN_pos
#check @NumStability.Ch15.SmoothPNormPair.pN_zero
#check @NumStability.Ch15.SmoothPNormPair.q
#check @NumStability.Ch15.SmoothPNormPair.rec
#check @NumStability.Ch15.SmoothPNormPair.recOn
#check @NumStability.Ch15.SmoothPNormPair.two
#check @NumStability.Ch15.dualq_one
#check @NumStability.Ch15.dualq_one_attains
#check @NumStability.Ch15.dualq_one_punit
#check @NumStability.Ch15.e0Vec
#check @NumStability.Ch15.eq15_3_F_two
#check @NumStability.Ch15.eq15_3_directional_two
#check @NumStability.Ch15.eq15_3_gradient_two
#check @NumStability.Ch15.eq15_4_counterexampleA
#check @NumStability.Ch15.eq15_4_counterexampleX
#check @NumStability.Ch15.eq15_4_counterexampleX_norm
#check @NumStability.Ch15.eq15_4_counterexample_dp_x
#check @NumStability.Ch15.eq15_4_counterexample_dq_z
#check @NumStability.Ch15.eq15_4_counterexample_satisfies_KKT
#check @NumStability.Ch15.eq15_4_counterexample_y
#check @NumStability.Ch15.eq15_4_counterexample_y_norm
#check @NumStability.Ch15.eq15_4_counterexample_z
#check @NumStability.Ch15.eq15_4_literal_counterexample
#check @NumStability.Ch15.eq15_4_normalize2_one
#check @NumStability.Ch15.eq15_4_normalize2_two
#check @NumStability.Ch15.gammaSeq_one_le_oneNorm
#check @NumStability.Ch15.gammaSeq_one_mono
#check @NumStability.Ch15.gammaSeq_two_le_opNorm2
#check @NumStability.Ch15.gammaSeq_two_mono
#check @NumStability.Ch15.holder_one
#check @NumStability.Ch15.holder_two
#check @NumStability.Ch15.lemma152_one
#check @NumStability.Ch15.lemma152_two
#check @NumStability.Ch15.lemma152b_strict
#check @NumStability.Ch15.normalize2
#check @NumStability.Ch15.normalize2_attains
#check @NumStability.Ch15.normalize2_unit
#check @NumStability.Ch15.opBound_two
#check @NumStability.Ch15.pNormPair_one
#check @NumStability.Ch15.pNormPair_two
#check @NumStability.Ch15.sign_attains_one
#check @NumStability.Ch15.sign_qunit_one
#check @NumStability.Ch15.unique_subgradient_of_directional_gradient
#check @NumStability.Ch15.vecNorm2_e0
#check @NumStability.Ch15.vecNorm2_hasDirectionalGradientAt
#check @NumStability.Ch15.vecNorm2_pos_of_ne
