import NumStability.Algorithms.MatrixEquations.Sylvester.Conditioning.StructuredSylvester
import NumStability.Algorithms.MatrixEquations.Sylvester.Equation.Diagonal
import NumStability.Algorithms.MatrixEquations.Sylvester.Conditioning.FirstOrder
import NumStability.Algorithms.MatrixEquations.Sylvester.Perturbation.Basic
import NumStability.Source.Higham.Chapter16.Section04.PracticalErrorBounds.SchurTransformClosure
import NumStability.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation22
import NumStability.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation25
import NumStability.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation27
import NumStability.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation23
import NumStability.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation24

/-!
# Algorithms.Sylvester.Higham16Psi

Historical compatibility facade for the W05 semantic modules.
-/
