import NumStability.Algorithms.MatMul
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.Executor
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.EndToEnd
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.ResidualAssembly
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.RoundedSolve
import NumStability.Algorithms.LinearSystems.Triangular.BackSubstitution
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.QuasiQuasiSolve
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.SmallSystemRounding
import NumStability.Analysis.Rounding
import NumStability.Source.Higham.Chapter16.Section04.PracticalErrorBounds.SchurTransformClosure
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equation09.Assembly
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equation09.EndToEnd
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.SpectralCompletion
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedTriangular
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedSylvesterCompletion
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.QuasiQuasiSylvester
import NumStability.Source.Higham.Chapter19.Core
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedExecutor

/-!
# Algorithms.Sylvester.Higham16RoundedExecutor

Historical import-only compatibility facade for the W06 semantic modules.
-/
