import NumStability.Algorithms.LU.GaussianElimination
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.PivotedSmallBlocks.CompletePivot
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.QuasiQuasiSolve
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.SmallSystemRounding
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedSylvesterCompletion
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.QuasiQuasiSylvester
import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.PivotedSmallBlocks

/-!
# Algorithms.Sylvester.Higham16PivotedSmallBlocks

Historical import-only compatibility facade for the W06 semantic modules.
-/
