import NumStability.Algorithms.PolynomialEvaluation.ComplexHorner.ErrorBounds

#check @NumStability.fl_complexAdd_output_error_bound_gamma2
#check @NumStability.fl_complexHornerStep_inverse_error_bound
#check @NumStability.fl_complexHornerRunningBound_nonneg
#check @NumStability.fl_complexHornerRunningStep_error_bound
#check @NumStability.fl_complexHornerRunningFold_error_bound
#check @NumStability.fl_complexHornerDesc_running_error_bound
