import NumStability.Source.Higham.Chapter11.SymmetricIndefinite.BunchKaufman.Rounded.GrowthSolveError

#check NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_source
