import NumStability.Source.Higham.Chapter28.Section02.RealGinibre.FiniteExpectation.CharacteristicProductMoments

/-!
# R09 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.integrable_ginibreComplexShiftedDeterminantPermutationTerm_mul
#check @NumStability.integrable_ginibreComplexShiftedPermutationPairMonomial
#check @NumStability.integrable_ginibreDeterminantPermutationTerm_mul
#check @NumStability.integrable_ginibrePermutationPairMonomial
#check @NumStability.integrable_ginibreShiftedDeterminantPermutationTerm_mul
#check @NumStability.integrable_ginibreShiftedPermutationPairMonomial
#check @NumStability.integrable_realGinibre_characteristicProduct
#check @NumStability.integrable_realGinibre_det_sub_smul_one_mul_det_sub_smul_one
#check @NumStability.integral_ginibreComplexShiftedDeterminantPermutationTerm_mul
#check @NumStability.integral_ginibreComplexShiftedPermutationPairMonomial
#check @NumStability.integral_ginibreDeterminantPermutationTerm_mul
#check @NumStability.integral_ginibrePermutationPairMonomial
#check @NumStability.integral_ginibreShiftedDeterminantPermutationTerm_mul
#check @NumStability.integral_ginibreShiftedPermutationPairMonomial
#check @NumStability.integral_realGinibre_characteristicProduct
#check @NumStability.integral_realGinibre_characteristicProduct_complex
#check @NumStability.integral_realGinibre_characteristicProduct_complex_eq_sum_fixedPoints
#check @NumStability.integral_realGinibre_characteristicProduct_conj
#check @NumStability.integral_realGinibre_characteristicProduct_eq_kernel
#check @NumStability.integral_realGinibre_characteristicProduct_eq_sum_fixedPoints
#check @NumStability.integral_realGinibre_coordinateProduct
#check @NumStability.integral_realGinibre_coordinateProduct_complex
#check @NumStability.integral_realGinibre_det_sq
#check @NumStability.integral_realGinibre_det_sub_smul_one_mul_det_sub_smul_one
