import NumStability.Source.Higham.Chapter11.Higham11BunchKaufmanExplicitInverseTerminalClosedForm

/-!
# R06 historical-only test — `Higham11BunchKaufmanExplicitInverseTerminalClosedForm`

Imports exactly the historical path; checks its preserved public
surface (6 declarations).
-/

#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_explicitInverse_dimension
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_explicitInverse_source_dimension
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_explicitInverse_source_firstOrder
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_explicitInverse_source_maxEntryNorm
#check @NumStability.Higham11RoundedBunchKaufmanExecution.computedSolve_backward_error_normwise_forty_actual_explicitInverse_source_polynomial
#check @NumStability.Higham11RoundedBunchKaufmanExecution.solveResidualCoefficient_threeHundredSixty_mul_u_le_linear_add_quadratic
