import NumStability.Algorithms.Sylvester.Higham16VecNorm

/-!
# R06 historical-only test — `Higham16VecNorm`

Imports exactly the historical path; checks its preserved public
surface (48 declarations).
-/

#check @NumStability.H16_eq16_3_existsUnique_isSylvesterSolutionRect_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_existsUnique_isSylvesterSolutionRect_of_no_common_complex_right_eigenvalue
#check @NumStability.H16_eq16_3_existsUnique_sylvesterVecCoeff_mulVec_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_existsUnique_sylvesterVecCoeff_mulVec_of_no_common_complex_right_eigenvalue
#check @NumStability.H16_eq16_3_existsUnique_sylvesterVecCoeff_nonsingInv_mulVec_solution_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_existsUnique_sylvesterVecCoeff_nonsingInv_mulVec_solution_of_no_common_complex_right_eigenvalue
#check @NumStability.H16_eq16_3_sylvesterVecCoeff_mulVec_bijective_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_sylvesterVecCoeff_mulVec_eq_zero_iff_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_sylvesterVecCoeff_mulVec_injective_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_3_sylvesterVecCoeff_mulVec_surjective_of_no_common_complex_eigenpair
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_operator_sigmaMin
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_pos_le_sylvesterSepInf
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_sepLowerBound
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_gram_eigenvalues
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_left_inverse_finiteOpNorm2Le
#check @NumStability.H16_eq16_4_8_existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_sigmaMin
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_operator_sigmaMin
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_pos_le_sylvesterSepInf
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_sepLowerBound
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_gram_eigenvalues
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_left_inverse_finiteOpNorm2Le
#check @NumStability.H16_eq16_4_8_exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_sigmaMin
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_no_common_complex_eigenpair
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_no_common_complex_right_eigenvalue
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_operator_sigmaMin_generated_step_formula_witness
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_pos_le_sylvesterSepInf_generated_step_formula_witness
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_sepLowerBound_generated_step_formula_witness
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_gram_eigenvalues_generated_step_formula_witness
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_left_inverse_finiteOpNorm2Le_generated_step_formula_witness
#check @NumStability.existsUnique_isSylvesterSolutionRect_of_realQuasiSchur_schedule_vecCoeff_sigmaMin_generated_step_formula_witness
#check @NumStability.existsUnique_sylvesterVecCoeff_mulVec_of_no_common_complex_eigenpair
#check @NumStability.existsUnique_sylvesterVecCoeff_mulVec_of_no_common_complex_right_eigenvalue
#check @NumStability.existsUnique_sylvesterVecCoeff_nonsingInv_mulVec_solution_of_no_common_complex_eigenpair
#check @NumStability.existsUnique_sylvesterVecCoeff_nonsingInv_mulVec_solution_of_no_common_complex_right_eigenvalue
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_operator_sigmaMin
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_pos_le_sylvesterSepInf
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_sepLowerBound
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_gram_eigenvalues
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_left_inverse_finiteOpNorm2Le
#check @NumStability.exists_realQuasiSchur_schedule_original_solution_and_generated_step_formula_of_vecCoeff_sigmaMin
#check @NumStability.sylvesterVecCoeff_mulVec_bijective_of_no_common_complex_eigenpair
#check @NumStability.sylvesterVecCoeff_mulVec_bijective_of_no_common_complex_right_eigenvalue
#check @NumStability.sylvesterVecCoeff_mulVec_eq_zero_iff_of_no_common_complex_eigenpair
#check @NumStability.sylvesterVecCoeff_mulVec_eq_zero_iff_of_no_common_complex_right_eigenvalue
#check @NumStability.sylvesterVecCoeff_mulVec_injective_of_no_common_complex_eigenpair
#check @NumStability.sylvesterVecCoeff_mulVec_injective_of_no_common_complex_right_eigenvalue
#check @NumStability.sylvesterVecCoeff_mulVec_surjective_of_no_common_complex_eigenpair
#check @NumStability.sylvesterVecCoeff_mulVec_surjective_of_no_common_complex_right_eigenvalue
