import NumStability.Algorithms.RandNLA.ElementwiseSpectral

/-!
# R10 old_only test

isolated historical import preserves the exact supported declaration surface
-/

#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactEntrywiseEvent_ge_one_sub
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactFrobEvent_ge_one_sub
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_cover
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_entrywise
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_frob
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_cover
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_entrywise
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_frob
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralRadius_ge_one_sub_delta_frob_explicit_gamma_square
#check @NumStability.sqMagTraceProbability_eventProb_elementwiseTraceResidual_entry_abs_le_ge_one_sub
#check @NumStability.sqMagTraceProbability_eventProb_fl_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub
#check @NumStability.sqMagTraceProbability_eventProb_forall_fl_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub_sum
#check @NumStability.sqMagTraceProbability_eventProb_forall_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub_sum
#check @NumStability.sqMagTraceProbability_eventProb_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub
#check @NumStability.sqMagTraceProbability_expectationReal_elementwiseTraceResidual_entry_sq_le
#check @NumStability.sqMagTraceProbability_expectationReal_elementwiseTraceResidual_frob_sq_le
#check @NumStability.sqMagTraceProbability_expectationReal_vecNorm2Sq_rectMatMulVec_elementwiseTraceResidual_le
