import NumStability.Algorithms.RandNLA.LeastSquaresSketch

/-!
# R10 old_only test

isolated historical import preserves the exact supported declaration surface
-/

#check @NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_augmentedSpan
#check @NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_coordinate_quadratic_error
#check @NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_idBasis
#check @NumStability.leverageTraceProbability_eventProb_lsObjective_le_one_add_eta_of_coordinate_quadratic_error
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_augmentedSpan
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_idBasis
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_residual_coordinates
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_residualsInColumnSpace
