import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.HitCounts.Bounds
import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.SpectralTransfer.Elementwise
import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.Elementwise
import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.LeverageScore
import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.RowNorm
import NumStability.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.UniformRows
import NumStability.Algorithms.RandomizedLinearAlgebra.LeastSquaresSketching.Objectives.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.LeastSquaresSketching.RowSampling.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.LowRankApproximation.ColumnSketches.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.LowRankApproximation.RankFactorizations.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Preconditioning.ExactTransforms.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Preconditioning.ExactTransforms.UniformRowComposition
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.Elementwise.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.LeverageScore.ComputedBasis
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.LeverageScore.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Gram
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.Core
import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.FloatingPoint

/-!
# Randomized numerical linear algebra

Reusable sampling, concentration, sketching, low-rank approximation, and
preconditioning APIs. This aggregate intentionally excludes source
correspondence and imports canonical reusable owners only.
-/
