import NumStability.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramMoments

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.countSketchProbability_eventProb_abs_rowGram_quadratic_error_le_ge_one_sub
#check @NumStability.countSketchProbability_eventProb_abs_rowGram_quadratic_error_le_ge_one_sub_delta_of_coeff_budget
#check @NumStability.countSketchProbability_eventProb_forall_abs_rowGram_quadratic_error_le_ge_one_sub_delta_of_sum_coeff_budget
#check @NumStability.countSketchProbability_eventProb_forall_abs_rowGram_quadratic_error_le_ge_one_sub_sum_coeff_budget
#check @NumStability.countSketchProbability_eventProb_forall_abs_rowGram_quadratic_error_le_ge_one_sub_sum_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_forall_abs_rowGram_quadratic_error_le_ge_one_sub_sum_vecNorm_budget
#check @NumStability.countSketchProbability_eventProb_rowGram_frob_error_le_ge_one_sub
#check @NumStability.countSketchProbability_expectationReal_rowGram_entry_error_sq_le
#check @NumStability.countSketchProbability_expectationReal_rowGram_frob_error_sq_le
#check @NumStability.countSketchProbability_expectationReal_rowGram_quadratic_error_sq_le
#check @NumStability.countSketchProbability_expectationReal_rowGram_quadratic_error_sq_le_frobNorm
#check @NumStability.countSketchProbability_expectationReal_rowGram_quadratic_error_sq_le_vecNorm
