import NumStability.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramLoewnerCovers

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignAddZeroRightPermuted_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignAddZeroRightTree_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignAddZeroRight_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignAddZeroRight_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignPermuted_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignSubZeroRightPermuted_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignSubZeroRightTree_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignSubZeroRight_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignSubZeroRight_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSignTree_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithFlStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSignPermuted_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSignPermuted_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSignTree_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSignTree_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_gridNorm_add_nat_orthonormal
#check @NumStability.countSketchProbability_eventProb_flSparseGramDotWithStoredSign_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_frob_error_le_ge_one_sub
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_frob_error_le_ge_one_sub_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_frob_error_le_ge_one_sub_orthonormal
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_cover_ge_one_sub_delta_of_sum_coeff_add_frob_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_cover_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_cover_ge_one_sub_sum_coeff_add_frob
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_cover_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub_delta_of_coeff_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub_delta_of_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub_delta_of_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub_frobNorm
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_ge_one_sub_orthonormal
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_gridNorm_add_nat_orthonormal
#check @NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_cover_ge_one_sub_delta_of_sum_coeff_add_frob_budget
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_cover_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_cover_ge_one_sub_sum_coeff_add_frob
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_cover_ge_one_sub_sum_vecNorm_add_frobNorm
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_gridNorm_add_nat_orthonormal_budget
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_productGrid_ge_one_sub_delta_of_sum_vecNorm_add_frobNorm_budget
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_gridNorm_add_nat_orthonormal
#check @NumStability.countSketchProbability_eventProb_rowGram_twoSidedLoewner_productGrid_ge_one_sub_sum_vecNorm_add_frobNorm
