import NumStability.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramDotFloatingPoint

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDotWithComputedDen_rowGram_frob_error_le_ge_one_sub
#check @NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDotWithComputedDen_rowGram_frob_error_le_ge_one_sub_frobNorm
#check @NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDot_rowGram_frob_error_le_ge_one_sub
#check @NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDot_rowGram_frob_error_le_ge_one_sub_frobNorm
