import NumStability.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.SampledGramEndpoints

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.rowSqNormTraceProbMass_marginal_two_ne
#check @NumStability.rowSqNormTraceProbability_eventProb_computedGram_frob_error_le_epsilon_add_tau
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGramDotWithComputedDen_frob_error_le_epsilon_add_explicit_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGramDot_frob_error_le_epsilon_add_explicit_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGramWithComputedDen_frob_error_le_epsilon_add_explicit_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_explicit_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_scaling_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau_dot_zero
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau_of_entrywise_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau_of_forall
#check @NumStability.rowSqNormTraceProbability_eventProb_rowSampleGram_frob_error_le_epsilon
#check @NumStability.rowSqNormTraceProbability_eventProb_rowSampleGram_frob_error_le_epsilon_of_budget
#check @NumStability.rowSqNormTraceProbability_eventProb_rowSampleGram_frob_error_le_ge_one_sub
#check @NumStability.rowSqNormTraceProbability_eventProb_rowSketchGram_frob_error_le_epsilon_add_tau
#check @NumStability.rowSqNormTraceProbability_expectationReal_centered_sum_sq
#check @NumStability.rowSqNormTraceProbability_expectationReal_fl_rowSampleGram_frob_error_le_add_perturb
#check @NumStability.rowSqNormTraceProbability_expectationReal_rowSampleGram_entry_error_sq
#check @NumStability.rowSqNormTraceProbability_expectationReal_rowSampleGram_frob_error_le
#check @NumStability.rowSqNormTraceProbability_expectationReal_rowSampleGram_frob_error_sq_le
#check @NumStability.rowSqNormTraceProbability_expectationReal_rowSketchGram_frob_error_le_add_perturb
#check @NumStability.rowSqNormTraceProbability_expectationReal_sampleAverage_sub_mean_sq
