import NumStability.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.SketchedObjectiveBounds

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.leverageTraceProbability_eventProb_lsObjective_le_one_add_eta_of_coordinate_quadratic_error
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_augmentedSpan
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_idBasis
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_residual_coordinates
#check @NumStability.leverageTraceProbability_eventProb_rowSampleLSObjective_le_one_add_eta_of_residualsInColumnSpace
