import NumStability.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.SpectralEventEndpoints

/-!
# R10 canonical_only test

isolated canonical import checks representative routed declarations
-/

#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactFrobEvent_ge_one_sub
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_cover
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_entrywise
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1ExactSpectralEvent_ge_one_sub_frob
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_cover
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_entrywise
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralEvent_ge_one_sub_frob
#check @NumStability.sqMagTraceProbability_eventProb_algorithm1FlSpectralRadius_ge_one_sub_delta_frob_explicit_gamma_square
