import NumStability.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.TridiagonalInverseCompletion

/-!
# Canonical: `NumStability.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.TridiagonalInverseCompletion`

Imports only the canonical destination, with no compatibility module in
scope, so the relocated declarations are shown to stand on the canonical
surface alone.
-/

#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.casesOn
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.ctorIdx
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.factorRecurrences
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.mk
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.mk.inj
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.mk.injEq
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.mk.noConfusion
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.mk.sizeOf_spec
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.noConfusion
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.noConfusionType
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.rec
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.recOn
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.residualsAndNormalizations
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.rowAssembly
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.scanAdds
#check @NumStability.Higham15Problem15_6.Problem15_6OperationSchedule.weightProducts
#check @NumStability.Higham15Problem15_6.finVectorAt
#check @NumStability.Higham15Problem15_6.finVectorAt_of_lt
#check @NumStability.Higham15Problem15_6.prefixScanNat
#check @NumStability.Higham15Problem15_6.prefixScanNat_const_mul
#check @NumStability.Higham15Problem15_6.prefixScanNat_eq_sum
#check @NumStability.Higham15Problem15_6.prefix_suffix_scan_split
#check @NumStability.Higham15Problem15_6.problem15_6_absEvaluations
#check @NumStability.Higham15Problem15_6.problem15_6_absInvMul
#check @NumStability.Higham15Problem15_6.problem15_6_infNorm
#check @NumStability.Higham15Problem15_6.problem15_6_lowerWeight
#check @NumStability.Higham15Problem15_6.problem15_6_maxComparisons
#check @NumStability.Higham15Problem15_6.problem15_6_operationSchedule
#check @NumStability.Higham15Problem15_6.problem15_6_recurrenceScalarOps
#check @NumStability.Higham15Problem15_6.problem15_6_scalarOps
#check @NumStability.Higham15Problem15_6.problem15_6_scalarOps_exact
#check @NumStability.Higham15Problem15_6.problem15_6_scalarOps_linear
#check @NumStability.Higham15Problem15_6.problem15_6_scalarOps_one
#check @NumStability.Higham15Problem15_6.problem15_6_scalarOps_zero
#check @NumStability.Higham15Problem15_6.problem15_6_upperWeight
#check @NumStability.Higham15Problem15_6.reverseSuffixScanNat
#check @NumStability.Higham15Problem15_6.reverseSuffixScanNat_const_mul
#check @NumStability.Higham15Problem15_6.reverseSuffixScanNat_eq_sum
#check @NumStability.Higham15Problem15_6.reverseSuffixScanNat_eq_sum_Ico
