import NumStability.Source.Higham.Chapter13.Table01.ProductTransfers.Families

/-!
# Canonical-only destination: NumStability.Source.Higham.Chapter13.Table01.ProductTransfers.Families

Imports only the canonical destination and checks its exact routed public surface.
-/

#check @NumStability.higham13_table13_1_arbitrary_product_family_from_eq13_22_source_norms
#check @NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check @NumStability.higham13_table13_1_point_col_bdd_product_family_from_source_norms
#check @NumStability.higham13_table13_1_point_row_product_family_from_eq13_23_source_norms
#check @NumStability.higham13_table13_1_spd_product_family_from_eq13_24_source_norms
